### ISSUE TITLE
Registers?

### ISSUE THREAD

**Issue by fortes** [junegunn/fzf.vim#10]
Is it possible to hook up `registers` as a source? I tried the following:

```
function! s:mycommand_sink(cmd)
    let cmd = substitute(a:cmd, '\d..', '', 'g') 
    execute cmd
endfunction

function! s:commands(bang)
  redir => registers
  silent registers
  redir END
  let list = split(registers, '\n')
    call fzf#run({
                \ 'source':  reverse(extend(list[0:0], map(list[2:], 's:format_cmd(v:val)'))),
                \ 'sink':    function('s:mycommand_sink'),
                \ 'options': '--ansi -x --prompt "Registers> " ',
                \ 'window': 'aboveleft 20new'}, a:bang)
endfunction

command! -bang Registers call s:commands(<bang>0)
```

I don't really know VimScript though, so this code, not shockingly, does not work.

**Comment by junegunn** [comment]
So, what are you going to do with the selected register? A register can hold some text snippet or a macro. You can replay it if it holds a macro (`@a`), paste the content of it onto the buffer (`"ap`), or put some text into it (`"ay`), etc. A flat `:Registers` command may not be the best way to *use* registers.

You might want to check out https://github.com/junegunn/vim-peekaboo instead.

**Comment by fortes** [comment]
Wow, Peekaboo is awesome, thanks!

**Comment by nmercado1986** [comment]
@junegunn I just came back to this issue.
Although peekaboo partially solves the issue of previewing register contents, it still does not allow for fuzzy searching. Perhaps something to implement on top of peekaboo, but would be nice to be able to do fuzzy searching on the contents of registers, rather than scanning the long list for what I'm looking for. For example, an option or extra binding to open peekaboo in "fuzzy search" mode. Once hit Enter, you operate on the register selected.
E.g.:
With registers:
"a -> hello
"b -> world

Sequence:
"he
Should show only:
"a -> hello
as the selected one, then pressing <Enter> would close peekaboo and leave in operator-pending mode to paste, yank, delete, etc.

Also, scrolling down results with C-j and C-k (or C-n/ C-p) would be useful.

**Comment by justrajdeep** [comment]
Can we reopen this issue please?

**Comment by dagadbm** [comment]
not all fzf commands need to mandatorily do something or output something...
it can be ab it "counter intuitive" but i do a TON of searches on fzf and i never press enter to navigate to them.. I just want to check if stuff exists or not most of the times and then i hit the preview key and its enough for me...

so this is definitely something that makes sense to do

**Comment by chrisshroba** [comment]
If you're searching the contents of the registers, it seems like the two actions you'd want to perform would be pasting or executing as a macro - I can't think of a reason why you'd want to choose a register to yank into based on what is already in it. So perhaps there could be two new functions: `:RegistersPut` and `:RegistersExec`? And if yanking is desired, there could also be `:RegistersYank` and `:RegistersAppend`?

I may implement this myself soon - if there's interest I'd be happy to submit a PR here :)
