### ISSUE TITLE
Matching absolute matches first, if possible

### ISSUE THREAD

**Issue by shmup** [junegunn/fzf.vim#1004]
Such as this example:

![image](https://user-images.githubusercontent.com/118710/80735922-67adb980-8adf-11ea-8221-06483309532e.png)

I am interested in matching full names before partials, so in this case, `latency.js` as I'm filtering on `latency.js`

I imagine the entire list is sorted, and cursor/selection will always be on the bottom. Possibly there's no great solution for this, but I wanted to ask

**Comment by junegunn** [comment]
I'm working on tweaking the scoring algorithm so that a character after `/` (or any common delimiter characters) are preferred. So this will be covered in the next version.

<img width="680" alt="image" src="https://user-images.githubusercontent.com/700826/182011384-c3c4c22a-8766-4968-ab3d-fb08998dc775.png">

**Comment by shmup** [comment]
<3 @junegunn 

I wondered last night when I was grooming issues, if it was a bit silly to close them just because they went quiet. Thanks for re-opening if the issue felt relevant to your work!

**Comment by shmup** [comment]
@junegunn I tested `.32` and this is what I'm seeing:

![image](https://user-images.githubusercontent.com/118710/183778449-f467a41d-fdc7-4ebb-9605-66996f1a52f9.png)

This is my searching for `system` and it selecting `metric_system`, though there is a literal match right above it: `system`.

I think this ticket's spirit was about that idea, regarding searching for `latency.js` and it matching `job_latency.js` even though there was an actual `latency.js` in the list.

**Comment by junegunn** [comment]
This is what I'm seeing.

<img width="428" alt="image" src="https://user-images.githubusercontent.com/700826/183782526-8ebd1486-beb1-43c7-89a9-5b4c1306e9a4.png">

`printf 'metric_system\nsystem' | fzf -qsystem --height=4`

**Comment by shmup** [comment]
@junegunn yeah, same. Is this new change you made based on sorting then?

i.e. try this: `printf 'metric_system\nsystem' | fzf --no-sort -qsystem --height=4`

**Comment by junegunn** [comment]
> Is this new change you made based on sorting then?

Yes and no. Previous versions of fzf also prefer `system` because it's shorter (`--tiebreak=length`). But the change is noticeable when the lengths are the same.

```sh
printf 'metric_system\nsystem_metric' | fzf -qsystem --height=4
```

The previous versions scored the both items the same, and preferred `metric_system` because it appears before the other.
The new scoring algorithm prefers `system_metric` because of the increased bonus point at `s`.
