### ISSUE TITLE
opening a directory in a new tab?

### ISSUE THREAD

**Issue by nhooyr** [junegunn/fzf.vim#102]
I forked this repository to add my own custom sources and colors. One of which was `FASD`. Essentially it indexes every file I access (in neovim and zsh) and gives it a score. With my fzf source, I can go through the database and select which file I want. It's a great way to quickly navigate my most used files in my shell and neovim.

Only problem I'm having is that I can't seem to open directories in a new tab. I select it press `ctrl-t` and nothing happens. I can see the buffer loaded but no new tab. Then if I do select it again, it works.

**Comment by nhooyr** [comment]
I swear I put the link but anyways, relevant code is here https://github.com/nhooyr/fzf.vim/blob/master/autoload/fzf/vim.vim#L978-L990

**Comment by junegunn** [comment]
This is actually an issue of Vim itself. This doesn't work as expected:

```vim
try | tab split /bin | endtry
```

I was able to find [a thread on this topic](https://groups.google.com/d/msg/vim_use/EeQM4EWP7IY/yFrhedMDWCAJ), but no clear answer was given. An easy but not very satisfactory workaround to the problem is not to use try-block in common_sink.

**Comment by nhooyr** [comment]
I added this to the top of the loop in s:common_sink

```vim
if isdirectory(item)
   let item .= '/'
endif
```

And then I added the following to my `init.vim`

```vim
augroup _dirvish
  autocmd!
  autocmd BufReadCmd */ redraw
augroup END
```

Works well enough for me.

**Comment by nhooyr** [comment]
@junegunn could you add my fix into fzf's s:common_handler?

**Comment by junegunn** [comment]
@nhooyr Unfortunately it may not be so simple, considering Windows platform and `&shellslash` (and yes, fzf does work on Windows: https://github.com/junegunn/fzf/pull/785). And I hope that the problem is properly addressed in Vim in the first place.

Can you do it in your source command/function instead?

**Comment by nhooyr** [comment]
If I do it in my source, I have to duplicate a lot of `fzf#wrap`. Could you just add a quick option then so it is opt in for now?

**Comment by junegunn** [comment]
No, I don't think you have to. You're only manipulating the input.

FYI, see https://github.com/junegunn/fzf/pull/771

I believe it should be trivial to write a filter command using Perl/Ruby/Python that processes FASD output and attaches `/` to directories.

**Comment by junegunn** [comment]
If the output of FASD is not large, you can consider processing it in Vimscript and pass it to `fzf#run` as a Vimscript list.

**Comment by nhooyr** [comment]
I just wrote a small script to do it, it's working great, thank you so much!

**Comment by nhooyr** [comment]
neovim/neovim#5933 :hooray:
