### ISSUE TITLE
Can i use fzf-complete-word to complete words from the current/opened buffers?

### ISSUE THREAD

**Issue by justrajdeep** [junegunn/fzf.vim#1040]
- [ x ] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ x ] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ x ] I have read through the manual page of fzf (`man fzf`)
- [ x ] I have searched through the existing issues

Hi 

Is it possible to use fzf-complete-word to complete words from the current/opened buffers?

This is an amazing plugin. I love it. Thanks :)

**Comment by junegunn** [comment]
No, but I believe you can implement your own completion for that using `fzf#vim#complete` function.

https://github.com/junegunn/fzf.vim#custom-completion

**Comment by pbnj** [comment]
I am not sure if there is a better way to do this, but here is what I came up with:

```viml
inoremap <expr> <C-k> fzf#vim#complete(fzf#wrap({
    \ 'source': uniq(sort(split(join(getline(1,'$'),"\n"),'\W\+'))),
    \ }))
```

- `getline(1,'$')` gets content of current buffer. Each line in the buffer is an item in an array
- `join(..., "\n")` joins the array with newlines
- `split(..., '\W\+')` splits the content into an array of words
- `sort(...)` sorts the array alphabetically 
- `uniq(...)` deduplicates the array. `uniq()` only deduplicates adjacent items, hence `sort(...)` (ref [this stackoverflow](https://stackoverflow.com/questions/6630860/remove-duplicates-from-a-list-in-vim/49596960#comment128676665_49596960)).

**Comment by xgpt** [comment]
This would be awesome. the regular word completion feels...lame after discovering fzf

**Comment by edemko** [comment]
In case anyone else happens across this issue, I've come up with a slight improvement. I was annoyed because the initially selected completion would always be just whatever word I was in the middle of typing (i.e. `ael<Tab>` would prefer `ael` to `addEventListener` even when `ael` was used nowhere else in the buffer). I don't think it'd take too much effort to adapt this script to accumulate all words from all open buffers that match the filetype, but it's late here and this is already as good as my old editor's completion. I suppose there's also a lot of room for improvement for what counts as a word, which might vary depending on the filetype.

Of course, you'll still have to `imap <Tab> <Plug>(fzf-complete-bufferword)`; I just keep that in a separate file for idk separation of concerns or smth.

```vimscript
function s:preceding_word()
  let p = getpos('.')[2]-1 " the minus 1 fixes up the one-indexing
  if p == 0
    return ""
  endif
  let line = getline('.')
  if match(line[p-1], '\W') == 0
    " the cursor is preceded by a non-word, so we don't want to throw away the
    " previous word
    return ""
  endif
  let words = split(line[0:p-1], '\W\+')
  if len(words) == 0
    return ""
  endif
  return words[-1]
endfunction

function s:buffer_words()
  let allwords = split(join(getline(1,'$'),"\n"),'\W\+')
  let prec = s:preceding_word()
  let i = index(allwords, prec)
  if i != -1
    let garbage = remove(allwords, i)
  endif
  " return join([i, prec, allwords], "\n")
  return allwords
endfunction

function s:completeBWords()
  return fzf#vim#complete(fzf#wrap({
    \ 'source': uniq(sort(s:buffer_words())),
    \ }))
endfunction

inoremap <expr> <silent> <Plug>(fzf-complete-bufferword) <sid>completeBWords()
```
