### ISSUE TITLE
Create file

### ISSUE THREAD

**Issue by tsigo** [junegunn/fzf.vim#107]
CtrlP [has a mapping](https://github.com/ctrlpvim/ctrlp.vim/blob/master/doc/ctrlp.txt#L377-L385) to create a file at the entered path and I'm wondering if there's an easy way to do this with fzf.vim.

**Comment by junegunn** [comment]
See the previous discussion here: #89
In short, I don't think creating a file from the "fuzzy" pattern makes sense (especially considering extended-search mode). I would just use `:e` for that purpose. You get proper path completion with that.

**Comment by Melkster** [comment]
@junegunn While I totally respect if this is something that you won't to implement, here's a use case where I would think it were awesome if I could create files directly from fzf.vim:

I have created a special mapping (`<leader>M`) that fuzzy searches inside the directory where I keep all my markdown notes, independently of my current working directory. For instance I tend to write drafts when I email people and I name the file after the person (`john-smith.md`) and I like to keep old email drafts in the file. It would be awesome if after I have fuzzy searched and found that the note I'm looking for doesn't exist yet I could then create a new file inside my notes directory without leaving fzf and having to navigate to the directory and create the file there using `:e`.

**Comment by novasenco** [comment]
agreed. annoying. would be nice if a mapping took path to current file and took its dirname (`fnamemodify(theFile, ':p')` in vim)

**Comment by j-hui** [comment]
lervag's wiki.vim plugin does something like this with its fzf wrapper: https://github.com/lervag/wiki.vim/blob/master/autoload/wiki/fzf.vim#L7

I adapted it to create my own `:Files`-like function; you can press `<C-j>` to create a file with the current query:

```vim
function! FzfFiles(fullscreen)                                            
  function! s:FzfFileAccept(lines) abort                                  
    " a:lines is a list with three elements (two if there were no matches):
    "   <search-query>, <expect-key>|<empty> [, <selected-items...>]      
    if len(a:lines) < 2                                                   
      return                                                              
    elseif len(a:lines) == 2 || !empty(a:lines[1]) |                      
      execute 'edit ' . a:lines[0]                                        
    else                                                                  
      execute 'edit ' . split(a:lines[2], '#####')[0]                     
    endif                                                                 
  endfunction                                                                                                      
  let l:spec = {                                                          
        \'options': ['-d=#####', '--print-query', '--expect=ctrl-j'],     
        \'sink*': funcref('s:FzfFileAccept')                              
        \}                                                                
  call fzf#vim#files(getcwd(), fzf#vim#with_preview(l:spec), a:fullscreen)
endfunction

" convenience bindings:
command! -bang Files :call FzfFiles(<bang>0)
nmap <leader>f :call FzfFiles(0)<CR>
```

**Comment by j-steinbach** [comment]
> I'm not quite sure how it makes sense for a fuzzy finder. (from #89)

FZF already acts beyond its finding capabilities -- it currently acts as a file finder _and opener_. If a user-preferred match is found, then the user opens the file. But what happens if _no_ user-preferred match is found? Currently the search just fizzles out. But the user usually starts the finding process with a specific intent in mind. This intent also covers alternatives in case the search fails -- unfortunately FZF doesn't offer any way to act on this intent. This is why this issue (and the previous one) exist.

Maybe I can simplify the above: Currently FZF does the following: 

Let the user search/find. IF something is found, then DO something else. 
But it doesn't cover failure mode: IF something is NOT found, then DO something else. 

Maybe this could be solved with a "hook". Let the user specify their own "alternate DO" function, provide them with the current search term and allow it to be called after a search.
