### ISSUE TITLE
[feature request] adaptive height for popup window

### ISSUE THREAD

**Issue by smartding** [junegunn/fzf.vim#1155]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I understand fzf.vim allows us to set relative and absolute height of pop up window, e.g.  with the following config
```vim
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6, 'border': 'sharp' } }
```
I wonder if it's possible to allow adaptive height, i.e. if we set height to `0`, then height of pop up window is based on number of items in the search result.

**Comment by junegunn** [comment]
We used to have (actually still have) adaptive height option for non-popup windows (e.g. `{ 'down': '~40%' }`), but I ended up undocumenting it, and I'll probably remove it from the code in the future. Reasons:

- fzf is an external process rather than a native Vim plugin
    - Dynamically resizing the Vim window from fzf is not viable
- fzf reads input asynchronously. Usually, it doesn't know how many items there will be
    - e.g. `:call fzf#run({ 'source': 'find /' })`
    - It wasn't particularly designed to be used with a fixed number of items.
- But when we use a list as the source from Vim, we do know the number in advance
    - e.g. `:call fzf#run({ 'source': [1, 2, 3] })`
- However, due to so many options fzf, we can't easily know how many lines are actually required to display exact N items on fzf.
    - `--info=inline`
    - `--header=some-header-string-that-may-span-multiple-lines`
    - `--header-lines N`
    - `--border STYLE`
    - `--margin TRBL`
- These options can come from `$FZF_DEFAULT_OPTS` and from `options` property of `fzf#run` spec.
- So unless the Vim plugin reimplements the option parser from the Go code, we can't know how tall the popup window should be.

So I gave up 😄
