### ISSUE TITLE
How to not have different color on currentline and first column when guibg=NONE ?

### ISSUE THREAD

**Issue by zdmgmail** [junegunn/fzf.vim#1187]
- [√] I have fzf 0.23.0 or above
- [√] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [√] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [√] I have read through the manual page of fzf (`man fzf`)
- [√] I have searched through the existing issues

![11-26_10:09:27](https://user-images.githubusercontent.com/50515839/100299810-8588c180-2fcf-11eb-9cbc-3c9333a51e1b.png)

I hope not have different color on current line and first column, and try to use 

```
:exe  'highlight  test      guifg=NONE  guibg='#3a3d4d'   guisp=NONE   gui=NONE   ctermfg=NONE  ctermbg=NONE   cterm=NONE'

let g:fzf_colors ={
 \ 'bg':      ['bg', 'test'],
\ 'bg+':     ['bg', 'test']}
```

If `guibg` not none, it's ok , but if `guibg=NONE`, it look like picture.

Is there a way use `guibg=NONE` but not have color on current line and first column?

**Comment by junegunn** [comment]
If you want to fine-tune the colors, you probably should put `--color` options in your `$FZF_DEFAULT_OPTS` instead of setting `g:fzf_colors`. `g:fzf_colors` is only useful if you often switch color schemes inside Vim and you want fzf colors to dynamically adapt to the current color scheme.

- Some examples: https://github.com/junegunn/fzf/wiki/Color-schemes
- Also see the description of `--color` option in `man fzf`
