### ISSUE TITLE
Preview of files in the buffer

### ISSUE THREAD

**Issue by uestueab** [junegunn/fzf.vim#1206]
- [x ] I have fzf 0.23.0 or above
- [ ] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ ] I have read through the manual page of fzf (`man fzf`)
- [ ] I have searched through the existing issues

Concerning [#799](https://github.com/junegunn/fzf.vim/issues/799) I'd like to know how to have a preview of the files in the buffer. What exactly do i have to add to my .vimrc to have that feature?

**Comment by cballam** [comment]
This should be on by default, with previews using [bat](https://github.com/sharkdp/bat). If you want to test using a custom command putting this in your .vimrc might work:

```
command! -bang -nargs=? -complete=dir Buffers
      \ call fzf#vim#buffers(<q-args>, fzf#vim#with_preview(), <bang>0)
```
With that open vim (and some buffers) and you should be able to call `:Buffers` to see options with a preview. As far as I'm aware this is basically reinventing the wheel since :Buffers effectively calls this by default, but this should explicitly tell it to preview files. See the vimdoc example for more info, I just swapped Files for Buffers: https://github.com/junegunn/fzf.vim/blob/master/doc/fzf-vim.txt#L250

**Comment by henryjetmundsen** [comment]
I'm not sure this addresses the issue that's being raised. I believe that @uestueab is asking for a feature like `Files`, except instead of showing all files in the directory which Vim was launched, it would show all files in the directory that the current buffer resides in. An example would be that I launch Vim in a folder called `my_project`, and then I open a file at `my_project/src/js/index.js`. If I run `Files` inside of this buffer, I will be prompted with all files contained in `my_project`. The desired behavior is to have a command, perhaps `BFiles`, which would show all files contained in `my_project/src/js`.

**Comment by cballam** [comment]
Perhaps I misinterpreted, the issue referenced mentions the `--preview` flag in the `:Buffers` command so I had assumed it was about the file previews when running a command. For files in the directory of the current buffer, the `:Files` command could be customized as per docs to use the working directory of the file open in the buffer:

https://github.com/junegunn/fzf.vim/blob/master/doc/fzf-vim.txt#L234

You can supply a directory as the first argument and I've put a quick example below to achieve that below with `:Files` (the `fzf#vim#with_preview` can be removed if desired):

```
command! -bang -nargs=? -complete=dir LocalFiles
     \ call fzf#vim#files(expand('%:h'), fzf#vim#with_preview(), <bang>0)
```
Calling :LocalFiles should then show all files in the relative file path of the file open in the current buffer.

**Comment by junegunn** [comment]
@cballam Thanks for the comment. Yes, preview is enabled by default for `:Buffers`. You don't need any configuration.
