### ISSUE TITLE
E488 using g:fzf_action for abort/close

### ISSUE THREAD

**Issue by gerardbm** [junegunn/fzf.vim#1285]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

When I configure a new action to close `:Files` with the same shortcut I use to open the menu (`Ctrl-f`), it returns the error E488. Example of my code:

```viml
let g:fzf_action = {
\ 'ctrl-t': 'tab split',
\ 'ctrl-s': 'split',
\ 'ctrl-v': 'vsplit',
\ 'ctrl-f': 'close'
\ }
```

It can't recognize `abort` or `close`, actions mentioned in the manual (`man fzf`).

**Comment by junegunn** [comment]
The values you put in this dictionary are Vim commands which are different from the "actions" in the man page.
I can see that it can be confusing because of the term `action`. 

Try adding `--bind` option to your `$FZF_DEFAULT_OPTS` like so

```vim
let $FZF_DEFAULT_OPTS = '--bind ctrl-f:close'
```

Also note that `CTRL-/` is set to `toggle-preview` by default in this plugin.
