### ISSUE TITLE
Feature Request: Use neovim's buffer as a previewer for true color and tree-sitter based syntax highlighting

### ISSUE THREAD

**Issue by shubhampaul** [junegunn/fzf.vim#1312]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Fzf uses bat for syntax highlighting which doesn't use vim's color scheme (or even true color themes) but Telescope has this functionality. Would it be possible to use vim buffers as a previewer for fzf so the preview is exactly how it would be if I open the file (basically matching nvim's theme with tree-sitter color selections)?

**Comment by bluz71** [comment]
fzf.vim basically runs the command-line tool, fzf, inside a (Neo)vim terminal, hence the previewer also needs to be a terminal program.

Neovim can't act as a fzf previewer in the command line since it takes over the entire screen. Hence, the reason why fzf defaults to using bat if available.

See [this discussion](https://github.com/junegunn/fzf.vim/issues/1043), it is basically the same issue as this one.

I believe you will find this will not be implemented since fzf.vim is mostly a terminal program and less a fully fledged (Neo)vim plugin.

If you really need treesitter highlighting then have a look at [telescope](https://github.com/nvim-telescope/telescope.nvim) and [Snap](https://github.com/camspiers/snap).

**Comment by shubhampaul** [comment]
Thanks for replying, (both on reddit and here), Telescope is slow compared to fzf so I cant use it for my large codebase, I was looking into snap and it looks quite promising. If I understand it correctly, it can use fzf as a backend but the preview is done using vim buffers? What I needs is fuzzy finding files/buffers with fzf (because its super fast) and doing a live grep with ripgrep with the treesitter syntax highlighting.

**Comment by bluz71** [comment]
@shubhampaul,

Note, if you care about performance above all else, then be aware that bat previewing is apparently much faster than Neovim with Treesitter (for big files).

I use fzf.vim in Neovim as against Telescope and Snap because fzf.vim works great, performance is always good and I very much like the git-delta display when doing git log or git diff viewing via fzf.

To get reasonable consistency between my Neovim colorscheme and bat I tweaked the existing base16 bat theme (which uses tmTheme format) and this is what I get with Ruby files:

- Neovim native with Treesitter:
![ruby](https://user-images.githubusercontent.com/11382509/127595723-d7cf535f-e7c0-4809-a082-9fd93da2043f.png)

- fzf.vim with bat previewing inside of Neovim using a tweaked base16 bat theme:
![ruby_In_bat](https://user-images.githubusercontent.com/11382509/127595734-e0d88778-d040-4487-afba-3b92f091d42e.png)

There are differences for sure, but for me they are close enough that I simply don't care to switch over to Telescope of Snap especially since fzf.vim still has the best performance and I can re-use my fzf knowledge in the command line (outside of Neovim).

But it is up to you, there are choices.

I would be recommend you close this since junegunn has already noted that your request is not possible to implement in fzf.vim.

**Comment by shubhampaul** [comment]
Yeah, it looks pretty close. I guess I need to tweak bat's theme. Thanks for the help.
