### ISSUE TITLE
Respect wildignore

### ISSUE THREAD

**Issue by hiquest** [junegunn/fzf.vim#133]
Is there a way to make FSF respect `wildignore` setting in `.vimrc` ?

This is really frustrating when it searches among `bower_components` or `node_modules`, etc...

**Comment by junegunn** [comment]
While we could theoretically do that, it's a bit of a hassle to parse the value and build a source command whose output we feed into fzf. I believe you're much better off with an external program that does the filtering. See
https://github.com/junegunn/fzf#respecting-gitignore-hgignore-and-svnignore

I personally use `ag --hidden --ignore .git -g ""`.

**Comment by megalithic** [comment]
I can see where `wildignores` would be useful; For instance, say you have a project with images, fonts, etc, you don't want to see those assets in the fuzzy finder results list when executing `:File`, but they do need to be managed by your VCS (you may update the images via photoshop or some such).

Thoughts? (I found this issue because I was wanting to do the exact same thing; e.g., use some separate list from .gitgnore, et al, to ignore certain filetypes that i'd never, EVER, open up within vim/)

**Comment by junegunn** [comment]
@megalithic One idea is to dynamically generate `agignore` file with the entries in `wildignore` and pass it to ag, i.e. `ag --path-to-agignore /tmp/agignore-for-fzf`. Since `:Files` command depends on `FZF_DEFAULT_COMMAND` which we have no control over, this can't be the default behavior.

```vim
function! s:with_agignore(bang, args)
  let agignore = '/tmp/agignore-for-fzf'
  let entries = split(&wildignore, ',')
  let source = 'ag --path-to-agignore '.agignore.' -g ""'
  call writefile(entries, agignore)
  call fzf#vim#files(a:args, extend(fzf#vim#layout(a:bang), {'source': source}))
endfunction

autocmd VimEnter * command! -bang -nargs=? -complete=dir Files
      \ call s:with_agignore(<bang>0, <q-args>)
```
