### ISSUE TITLE
RG command should respect fzf_actions 

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [junegunn/fzf.vim#1345]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

RG commands should also respect fzf_actions dict. including function calls, splits, etc.

**Comment by bruhtus** [comment]
Not sure about the function calls but the splits keybindings works for me with `:Rg` command too. I also remap the `g:fzf_action` to something like this (only changed the default vertical splits keybindings):
```vim
 let g:fzf_action = {
        \ 'ctrl-t': 'tab split',
        \ 'ctrl-x': 'split',
        \ 'ctrl-s': 'vsplit' }
```

Can you give more context how to reproduce the issue?

**Comment by ViRu-ThE-ViRuS** [comment]
@bruhtus thanks for your prompt response, let me try to explain what was happening:

``` lua
local utils = require("utils")

vim.g.fzf_preview_window = "right:50%:+{2}-/2"
vim.g.fzf_buffers_jump = 1
vim.g.fzf_layout = {["down"] = "40%"}

vim.g.fzf_action = {
    ["ctrl-q"] = utils.qf_populate,
    ["ctrl-x"] = "split",
    ["ctrl-v"] = "vsplit"
}

utils.map("n", "<c-p>p", "<cmd>Files<cr>")
utils.map("n", "<c-p>b", "<cmd>Buffers<cr>")
utils.map("n", "<c-p>f", "<cmd>Rg<cr>")
utils.map("n", "<c-p>z", "<cmd>Rg TODO<cr>")

vim.cmd [[
    let $FZF_DEFAULT_COMMAND = 'rg --files --follow --smart-case --hidden --no-ignore -g "!{.DS_Store,.cache,venv,.git,.clangd,.ccls-cache}" 2> /dev/null'
    let $FZF_DEFAULT_OPTS = '--bind ctrl-a:select-all,ctrl-d:deselect-all'

    augroup FZF_UI
        autocmd!
        autocmd User FzfStatusLine setlocal statusline=%!v:lua.StatusLine('FZF')
    augroup end
]]
```

this is how I setup fzf.vim, and the function `utils.qf_populate` sets the qflist (among some other things it does with the selected items). This works fine with 'Files' which doesnt make a qflist on its own when multiple things are selected, but with 'Rg', I make the qflist using my function, then fzf.vim makes one as well (overwriting the qflist behaviors I specified). 

Ideally, imho, the `action` should be responsible completely for what happens. So `rg` should not make a qflist if an action key is pressed (ie not show its default behavior).

In my case, I want the qflist made to have the following properties `nobuflisted`, `hidden="wipe"`, `number`, and `signcolumn="no"`. But I cannot do this with the current setup.

**Comment by ViRu-ThE-ViRuS** [comment]
having looked at the code, I can see this happens because FZF is calling the mappings, not fzf.vim. The handling functions for Rg/Ag do not make a call to fzf, thus special mappings cant take place. To get the behavior I mention above, one will need to set keymaps inside the fzf buffer for this command (or some other trick idk).

I understand if this functionality is beyond the scope of this plugin, and one can look into other plugins like `fzf-lua` and `nvim-fzf` but they are only for neovim users. If the author(s) would like to add more extensibility to this plugin, and allow their significant neovim user base more power, this will be a good starting feature to start the "modernization with".

I would volunteer to work on this and make a pr, but I dont know enough VIML to not break anything.

**Comment by junegunn** [comment]
`g:fzf_action` isn't for everything. Because the commands in the dictionary expect each line of fzf output to be a plain file path, we can't use it for different types of input. i.e. it doesn't make sense to `vsplit SOME-COLORSCHEME-NAME` (`:Colors`) or `tabedit getcurpos()` (`:Helptags`).

So basically we don't use it if a custom sink function (likely for non-filepath entries) is provided.

* https://github.com/junegunn/fzf/blob/master/README-VIM.md#global-options-supported-by-fzfwrap

```vim
" g:fzf_action applies because no custom sink function is provided
call fzf#run(fzf#wrap({'source': 'ls'}))

" Custom sink function is given. It probably means that the entries are not file paths.
" While that is not necessarily true, we don't blindly apply g:fzf_action hoping that it works.
call fzf#run(fzf#wrap({'source': 'seq 1000', 'sink': { line -> setline('.', str2nr(line) * 100) }}))
```

Rg, Tags, BLines, and many other commands in this project deal with non-simple-filepath entries, and because of that, fzf.vim has to implement different sink function for each one of them. Some of the functions try to support `g:fzf_action` as much as possible, but that's a lot of tedious work and there are cases where it's not clear how it should behave. e.g. We probably can't just call a custom sink function or command defined in `g:fzf_action` when we run `:Tags` or `:BTags` and expect it to work.
