### ISSUE TITLE
Weird glitch in popup window

### ISSUE THREAD

**Issue by chris542** [junegunn/fzf.vim#1370]
- [x] I have fzf 0.23.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

I always had this weird glitch when rendering the popup window on fzf, where the window spazzes whenever it opens. I thought it was due to too many files being loaded onto fzf finder.

But today i realised that there is a weird behaviour on my popup.

![ezgif-1-30a8cc03ac](https://user-images.githubusercontent.com/17423698/154916222-95fce04e-ead2-452e-8689-d517b745a801.gif)

As shown in the screenshot, there are only 3 outcomes, but the popup still makes a weird glitch.
Then I realised that popup window on the right side had a broken UI.
When I toggle open the preview window, it is more evident.

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/17423698/154915034-ec4073b2-d231-4c84-808f-c1c8031ab29a.png">

I tried removing all other plugins and removed all of my settings except fzf, but couldn't remove this issue.

here is the minimum settings

```
".plugins
filetype off                  " required

call plug#begin('~/.vim/plugged')

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'                                             " Fuzzy find files/content/tags
Plug 'neoclide/coc.nvim', {'branch': 'release', 'do': ':CocUpdate'}
"Plug 'antoinemadec/coc-fzf'                                         " Fzf for coc

call plug#end()

"-----------------------------------

".vimrc
"junegunn/fzf
set rtp+=~/.fzf
let $FZF_DEFAULT_OPTS="--layout=reverse --bind ctrl-k:preview-up,ctrl-j:preview-down,?:toggle-preview"
let $FZF_DEFAULT_COMMAND='rg --files --follow --no-ignore-vcs --hidden -g "!{node_modules/*,.git/*}"'
let g:fzf_layout={'window':{ 'width': 0.9, 'height': 0.6 }}
let g:fzf_preview_window = []
let g:fzf_action = {
            \ 'ctrl-t': 'tab split',
            \ 'ctrl-o': 'split',
            \ 'ctrl-v': 'vsplit' }
command! Ctrlp execute (exists("*fugitive#head") && len(fugitive#head())) ? ':GFiles' : ':Files'
nnoremap <silent> <C-p> :Ctrlp<CR>
nnoremap <silent> <C-e> :History<CR>
nnoremap <silent> <C-t> :Tags<CR>
nnoremap <Leader>f :Rg<space>
vnoremap <Leader>f y:Rg <c-r>"<cr>
nnoremap <Leader>F :Rg <c-r><c-w><cr>

autocmd! FileType fzf
autocmd! FileType fzf tnoremap <buffer> <esc> <c-c>
autocmd  FileType fzf set laststatus=0 noshowmode noruler
  \| autocmd BufLeave <buffer> set laststatus=2 showmode ruler

```

**Comment by junegunn** [comment]
What is the output of `:echo &ambiwidth`?

**Comment by chris542** [comment]
@junegunn `single`

**Comment by junegunn** [comment]
Is your terminal emulator capable of properly displaying box-drawing characters?

```sh
cat << EOF
╭─────────────────────────────────────────────────────╮
│                                                     │
│ https://en.wikipedia.org/wiki/Box-drawing_character │
│                                                     │
╰─────────────────────────────────────────────────────╯
EOF
```

**Comment by chris542** [comment]
@junegunn I've just tested on my terminal (iterm2) and it doesn't show broken side bar, but it still shows glitches.
It looks like the bar glitch is only present on macvim (v 8.2.3455 )

![asdfsd](https://user-images.githubusercontent.com/17423698/155061157-582c717e-8e3e-4b0e-8075-3ae092dfffa6.gif)

The gif shows `vim` first then `mvim` in comparison.

`vim` does not have the popup UI defect, but still has the glitch.
`mvim` has popup UI defect, and also has the glitch.

**Comment by chris542** [comment]
@junegunn should this be reported to macvim you reckon?

**Comment by junegunn** [comment]
I currently don't have macvim installed to confirm the case. You might want to open a terminal inside macvim (`:terminal`) and run [the above command](https://github.com/junegunn/fzf.vim/issues/1370#issuecomment-1047328141) I showed you and see if it properly displays the box.

If it doesn't, I would try changing the font of macvim to see if it helps. Or you could add `let $FZF_DEFAULT_OPTS='--no-unicode'` to your Vim configuration file so that fzf doesn't use unicode box-drawing chars.

**Comment by chris542** [comment]
@junegunn thank you! i guess the issue was from my font? 
Entering `:terminal` in macvim also showed the similar issues only on macvim terminal. I added `--no-unicode` and it fixed the issue.
Looks slightly uglier than before but looks more like vim style anyways :)

it hasn't solved the flickering issue, but the UI looks much better now.

Do you know what could be causing the flickering btw?

**Comment by dorukozerr** [comment]
I had the same issue, I noticed that it gets worse on high resolutions and disappear on lower resolutions.

`echo &ambiwidth` output is single

I tested with iterm2, macos terminal app, and wezterm while inside and outside of tmux sessions. I'm using my screen res in 2294x1490.

When I increase the font-size of my terminal a lot this issue doesn't happens or I keep default font size and decrease the preview window dimensions again it does not happen. I think it might be caused by high screen res and stuff to render on it.

When I was randomly trying some stuff I I found out that using tmux for preview window fixes the issue.

```vim
if exists('$TMUX')
  let g:fzf_layout = { 'tmux': '100%,100%' }
else
  let g:fzf_layout = { 'window': { 'width': 1, 'height': 1 } }
endif
```

Outside of tmux it still glitching but I always use tmux so it's ok.

First screen recording with `let g:fzf_layout = { 'window': { 'width': 1, 'height': 1 } }` config only second one is with `let g:fzf_layout = { 'tmux': '100%,100%' }` only.

https://github.com/user-attachments/assets/b08d594e-45a9-458f-8431-1cbcff5d0d44

https://github.com/user-attachments/assets/70eb03c0-f57d-492c-b94f-dccfb3210144
