### ISSUE TITLE
Command failed: git -C '/home/...' ls-files -z --deduplicate

### ISSUE THREAD

**Issue by coffeebe4code** [junegunn/fzf.vim#1446]
- [ x ] I have fzf 0.30.0 or above
- [ x ] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [ x ] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [ x ] I have read through the manual page of fzf (`man fzf`)
- [ x ] I have searched through the existing issues

Start Vim with a minimal configuration
======================================

vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)

This issue persists with the minimal configuration.
I did a PlugUpdate which would pull the latest fzf, ever since then, any directory I open and run `:GitFiles` that is a git directory, i get this issue.
```
Command failed: git -C '/home/user/git-repo-for-sure' ls-files -z --deduplicate
```

**Comment by coffeebe4code** [comment]
I ran the command that failed, and it appears --deduplicate is not an option for git.

I have been running the default setup for fzf for several years, is this a new change? Do I need to do anything?

**Comment by kmcgahee** [comment]
I'm seeing this issue as well. I'm on 

```
fzf --version
0.27.0 (19759ed)

git --version
git version 2.25.1

NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by junegunn** [comment]
531dd67350331771c0c099e9682a05744149e7b9 replaced `uniq` with `--deduplicate` option to filter out duplicates from `git ls-files`, because some versions of `uniq` are not capable of handling NUL-character-terminated lists.

But it turns out `--deduplicate` is a relatively recent addition to git, only available on 2.31 or above. https://github.com/junegunn/fzf.vim/commit/fd7fab77b20fdf09180cabdd660d8c3b7fe7ca1a fixed it by not using the option on older git versions, but that means you may see duplicates, unless you upgrade your git version.

**Comment by coffeebe4code** [comment]
Updating with `sudo apt install git`. Removing `fzf` and `fzf.vim` Plug lines, reloading vim and running `:PlugClean`, then adding fzf.vim and fzf back to my vimrc, reloading vim once again, and running `:PlugInstall` once again resolved the issue, as it forced fzf and git to be at the latest

**Comment by junegunn** [comment]
No need to remove and reinstall. You can just just run `:PlugUpdate`.
