### ISSUE TITLE
Unable to use commands like :Files and :Buffers

### ISSUE THREAD

**Issue by obsessed-af** [junegunn/fzf.vim#1498]
- [x] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Hi. I installed the plug via vim-plug and have the latest version of fzf and neovim.
I can't use any of the commands listed in the README, such as `:Files` and `:Buffers`. It seems to be undefined for me. I've searched through the README of fzf and the plugin (here). I also searched through the issues but couldn't find anything related to what I want. I know it's out there, but I couldn't find anything. Any help would be appreciated!

**Comment by blockloop** [comment]
This seems like a recent change caused this. I've always been able to use `:Files`, but not any more.

**Comment by bruhtus** [comment]
@obsessed-af Can you put the error message here? Also, could you check if `fzf.vim` plugin already loaded using `:echo g:loaded_fzf_vim` (if it throw an error, then the plugin is not loaded). From your description, if the command is undefined, it could be because the plugin is not loaded but to make that clear, we should check the error message.

**Comment by junegunn** [comment]
Please post your .vimrc so I can check if there's any error.

**Comment by 202211150054** [comment]
I also have this problem, it seems that the files in the "autoload" directory have not been successfully downloaded to my computer.
