### ISSUE TITLE
Perform different sink actions on Enter and Shift+Enter

### ISSUE THREAD

**Issue by pabsan-0** [junegunn/fzf.vim#1535]
- [ ] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

---
Hi, I want different actions to be performed with Enter and ShiftEnter. 

I'm using fzf to fuzzyfind snippets and would like Enter to copy snippets into my current file and ShiftEnter to edit them. This is what my vimrc lines look like:
```
let s:snippets_path = "~/snippets/"

function! s:rg_file_read(location)
    let string_list = split(a:location, ':', 2)
    execute 'read ' .. s:snippets_path .. string_list[0]
endfunction

command! -bang -nargs=* CustomSnippets
    \ call fzf#vim#grep(
    \ "rg -m 1 -L --column --no-heading --pretty --smart-case ".shellescape(<q-args>), 
    \ 1, 
    \ fzf#vim#with_preview({'dir': s:snippets_path, 'sink': function('s:rg_file_read')}),
    \ <bang>0)
```

From `man fzf` the alternate action could be done on the CLI via something like `fzf --bind "enter:execute(less {})"`, but I can't figure how to port that into vim. Could you please provide some pointers?

**Comment by junegunn** [comment]
* Since you're providing your own `sink` function, there's no need to use `fzf#vim#grep`. The basic `fzf#run` is a better fit here.
    * Reference: https://github.com/junegunn/fzf/blob/master/README-VIM.md
* CTRL-enter is not a key a regular terminal can recognize, so fzf doesn't support it, but you can use `alt-enter`
* Use `--expect=alt-enter` to make fzf print it as the first line when you press it. If you press enter, the first line will be an empty line.
* The sink function has to process two lines, 1. the name of the key pressed, 2. and the selected file name. Use `sink*` instead of `sink`.
* You can make fzf skip over the unwanted lines by using `transform` action bound to `focus` event. This will however, make the cursor movement a little bit slower because fzf will constantly run a shell command.

```vim
let s:snippets_path = "~/snippets/"

function! s:rg_file_read(lines)
  if len(a:lines) < 2
    return
  endif

  let [key, file] = a:lines
  if key == 'alt-enter'
    execute 'tabedit' file
  else
    execute 'read ' .. s:snippets_path .. file
  endif
endfunction

command! -bang -nargs=* CustomSnippets
    \ call fzf#run(fzf#vim#with_preview({
    \   'source': "rg -m 1 -L --no-heading --pretty --smart-case ".shellescape(<q-args>),
    \   'options': ['--reverse', '--ansi', '--expect=alt-enter', '--bind', 'focus:transform:[[ -n {} ]] && [[ ! {} =~ : ]] && exit; [[ $FZF_ACTION =~ up$ ]] && echo up || echo down'],
    \   'dir': s:snippets_path,
    \   'sink*': function('s:rg_file_read')
    \ }, <bang>0))
```
