### ISSUE TITLE
Get current fzf.vim colorscheme

### ISSUE THREAD

**Issue by aignacio** [junegunn/fzf.vim#1559]
### Checklist

- [X] I have fzf 0.54.0 or later
- [X] I have searched through the existing issues

### Output of `:echo system(fzf#exec() .. ' --version')`

0.54.3 (brew)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Problem / Steps to reproduce

Hey,

how can I obtain fzf.vim default colorscheme? I'd like to change my vim colorscheme to match fzf.vim current preview window.

Thanks!

<img width="1639" alt="image" src="https://github.com/user-attachments/assets/9f2927dc-4e36-4cc3-9cd1-bc5962af7f90">

**Comment by junegunn** [comment]
fzf uses [`bat`](https://github.com/sharkdp/bat) to display syntax-highlighted preview, and if I'm not mistaken, the default theme of bat is 'Monokai Extended'. So here it is: https://github.com/patstockwell/vim-monokai-tasty 

---

But looking at the attached image, it looks like you're already using `monokai`...? Are you asking how you can change the colors of fzf itself to match monokai? There is no official monokai color settings for fzf and you have to make one yourself. See these links to get started.

* https://github.com/junegunn/fzf/blob/master/ADVANCED.md#color-themes
* https://github.com/junegunn/fzf/blob/master/ADVANCED.md#generating-fzf-color-theme-from-vim-color-schemes

---

Or, if you're wondering how you can make Vim highlights elements exactly like bat, I don't think you can really achieve it, because Vim and bat use different methods to parse and syntax-highlight the code.

**Comment by aignacio** [comment]
> fzf uses [`bat`](https://github.com/sharkdp/bat) to display syntax-highlighted preview, and if I'm not mistaken, the default theme of bat is 'Monokai Extended'. So here it is: https://github.com/patstockwell/vim-monokai-tasty
> 
> But looking at the attached image, it looks like you're already using `monokai`...? Are you asking how you can change the colors of fzf itself to match monokai? There is no official monokai color settings for fzf and you have to make one yourself. See these links to get started.
> 
> * https://github.com/junegunn/fzf/blob/master/ADVANCED.md#color-themes
> * https://github.com/junegunn/fzf/blob/master/ADVANCED.md#generating-fzf-color-theme-from-vim-color-schemes
> 
> **Or, if you're wondering how you can make Vim highlights elements exactly like bat, I don't think you can really achieve it, because Vim and bat use different methods to parse and syntax-highlight the code.** <-- That is what I want to achieve =)

Thanks @junegunn, I was looking for the above answer! Will try to explore `bat` and see if there is a way to bring the same into vim, maybe through custom parsing.
