### ISSUE TITLE
Files ignores multiselection on Enter

### ISSUE THREAD

**Issue by vimpostor** [junegunn/fzf.vim#1560]
### Checklist

- [X] I have fzf 0.54.0 or later
- [X] I have searched through the existing issues

### Output of `:echo system(fzf#exec() .. ' --version')`

0.54.3 (af4917db)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Problem / Steps to reproduce

With many commands (for example the ripgrep search), multiselection is supported by default, i.e. one can multiselect with Tab, and when one presses Enter, all entries are added to the quickfix list.

With `:Files`, multiselection is possible, but when pressing Enter, it just opens the currently selected file. It would make much more sense to keep the commands consistent, and have `:Files` put the files in the quickfix list, if multiple are selected, as it doesn't make any sense to select multiple files just to open a single file.

Alternatively, the secondary keybinding on `Ctrl+Q` as described in `:h fzf-examples` could be made a default keybinding, so that users no longer need to write a separate Vimscript function.

**Comment by junegunn** [comment]
> it just opens the currently selected file

No, it opens all the selected files. Run `:ls` and you should be able to see they are listed. You can switch between the buffers using `:bprev`, `:bnext` or `:Buffers`. Because each selection from `:Files` doesn't point to a specific location in a file, quickfix or location list doesn't add much value.
