### ISSUE TITLE
Bug: directory name with colon causes file not found

### ISSUE THREAD

**Issue by serranomorante** [junegunn/fzf.vim#1575]
### Checklist

- [X] I have fzf 0.54.0 or later
- [X] I have searched through the existing issues

### Output of `:echo system(fzf#exec() .. ' --version')`

0.55.0 (fc693080)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Problem / Steps to reproduce

![image](https://github.com/user-attachments/assets/da02d8ad-3e33-4581-a221-d069534fbec9)

1. Clone [this repro](https://github.com/serranomorante/fzf_issue.git)
2. `cd fzf_issue`
3. Open nvim with `nvim --clean +'so repro.lua'` and wait for lazy.nvim to install dependencies
4. Execute `:Rg`
5. Try to enter any result file inside the `nvim-data-*` folders. It will open an empty buffer instead of opening the real file.

fzf.vim seems to not be parsing the directory names correctly.

This is not urgent for me, I can make the directory names to use another format but I'm still curious about this issue.

Thanks.

**Comment by junegunn** [comment]
That's because the preview script assumes that there are no colons in the path

https://github.com/junegunn/fzf.vim/blob/ec75ffbfd50630bf2b8d444d89487e149bacf7f3/bin/preview.sh#L20-L22

We would have to change the code to concatenate the leading elements delimited by colons, until it becomes a path that actually exists, but we currently don't do that for simplicity's sake.

**Comment by serranomorante** [comment]
Thanks! I already changed the format of my directory names as it might cause trouble with other software as well not only fzf.vim. I will close the issue now as probably the solution could be performance expensive.
