### ISSUE TITLE
Dosn't want to work for MacVim

### ISSUE THREAD

**Issue by travis2861** [junegunn/fzf.vim#16]
In regular old terminal vim loads up just fine testing with :Files command, in macvim testing the :Files command it hangs for a second then goes back to the line I was on with zero output at all.

**Comment by junegunn** [comment]
Since fzf is an external command-line program rather than a vim plugin written in vimscript, it cannot start inside macvim window. Instead, it starts an external terminal emulator which by default is xterm. It is likely that `xterm` is not installed on your system. Please refer to this issue: https://github.com/junegunn/fzf/issues/234

I fixed the problem where fzf does not print any message when it failed to start the "launcher". So if you update the main repo, you'll now see the message `Error running xterm -T ...`.

**Comment by junegunn** [comment]
By the way you can use iterm2 instead of xterm:
https://github.com/junegunn/fzf/wiki/On-MacVim-with-iTerm2

**Comment by travis2861** [comment]
Sorry for the late reply, on vacation atm. That fix worked perfectly thanks.
