### ISSUE TITLE
What command should I use to get BTags prompt back to the bottom of the window?

### ISSUE THREAD

**Issue by yevhen-m** [junegunn/fzf.vim#176]

**Comment by junegunn** [comment]
It's currently not customizable. But I can consider adding a config variable.

**Comment by yevhen-m** [comment]
Thanks.
But I would rather ask you to consider adding "prev/next" input support.
So, when I start `:Commands<CR>`, I can get my previous input with a mapping, say `<c-p>`, so I can browse input history back and forth. What do you think?

**Comment by junegunn** [comment]
That can be enabled using `--history HISTFILE` option of fzf (see man page for the details). You can put it in your `$FZF_DEFAULT_OPTS`, but then all the commands using fzf will share the same history which is obviously not desirable. In order to support command-wise history, we'll add `g:fzf_COMMAND_options` for each command you one can specify the name of the history for each command.

**Comment by yevhen-m** [comment]
Thanks, I'm waiting for this feature.

**Comment by junegunn** [comment]
https://gist.github.com/junegunn/f8a0b2712656867888e79397cc5cbffc

**Comment by yevhen-m** [comment]
Great, looking forward to trying it.

**Comment by yevhen-m** [comment]
Also, you consider adding setting `let g:fzf_history_dir = '~/.fzf-history'` by default. Now if you omit it in your .vimrc, c-n and c-p simply do nothing.

**Comment by junegunn** [comment]
They move the focus up and down inside fzf finder. I prefer the behavior and I rarely find myself wanting `--history` option.

Enabling the option will make fzf.vim write history files in the directory and some users will not like it.
