### ISSUE TITLE
Quick search for "cased" filenames

### ISSUE THREAD

**Issue by chrisnicola** [junegunn/fzf.vim#179]
- Category
    - [x] Question
    - [x] Suggestion
- Vim
    - [x] Vim
    - [x] Neovim

I'm curious if it is possible to search based on filename casing? A really common feature of many fuzzy finders to search for files based on an abbreviation of the words using the casing patters. For example:

`ccbb`

Would match on the first letters based on camel or snake casing such that it returns all the following files.

```
ChittyChittyBangBang.cs
chittyChittyBangBang.js
chitty_chitty_bang_bang.rb
chitty-chitty-bang-bang.md
```

Is this already possible through some configuration or not yet?

**Comment by junegunn** [comment]
For camel-cased entries, queries with uppercase letters (e.g. `CCBB` or `cCBB`) will most certainly do what you want because fzf performs "smart-case" search a la vim.

We give bonus to the letters at word boundaries, so snake-case entries tend to get ranked higher if other conditions are equal, but the bonus points we give are not great enough to overrule the basic ranking algorithm of fzf.

```sh
# snake-case is ranked higher
(echo 'snakeycase'; echo 'snake-case') | fzf -q sc

# but we don't choose it over more precise matches (shorter matchlen)
(echo 'snakecase'; echo 'snake-case') | fzf -q sc
```

There was an in-depth discussion and I did a series of experiments over the amount of the bonus, but I realized that larger bonuses can often produce confusing, non-intuitive results, so I decided to take the conservative approach described above which should feel more consistent and less surprising.

**Comment by chrisnicola** [comment]
Awesome. I'll play around with it a bit more. FZF with Neovim has been a huge improvement over CtrlP for me. Great work!
