### ISSUE TITLE
Keep FZF open after open a file

### ISSUE THREAD

**Issue by j5shi** [junegunn/fzf.vim#192]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ ] Neovim

I often use fzf to search string in a great amount of files, and it takes time to generate the cache, usually when I find the string, I will open the file in whcih the string is, and then fzf will quit, I wish fzf remain open after I open the file so that it can save time to reload/re-generate the cache.

Is this feature available already but I didn't find?

Thanks.

**Comment by edi9999** [comment]
It seems strange to me that fzf takes a lot of time to show you the results. Maybe you are looking into files that you are not interested in (node_modules, vendor files, build files, ...). For me, it always takes ~100ms to show the fzf with all lines in it.

I don't think it is easily possible to keep the fzf buffer opened after pressing enter, since we would need a way to communicate with vim (which neovim has, but this repo is for both).

If you really would like to cache the result of ag, here is how you could do : 

One way to do this is to really "cache" the output of ag, here is what you could do : 

Create a newfile cacheme in your path : 

```
#!/bin/bash

cachefile="/tmp/cache-file-$1"
shift 1

if [ -f "$cachefile" ]
then
	cat "$cachefile"
else
	"$@" | tee "$cachefile"
fi
```

Then, move your ag binary to `ag-uncached`

Then create a file in your path called `ag`, which is : 

```
#!/bin/bash
cacheme ag "$@"
```

**Comment by junegunn** [comment]
I also would like it, but it's not trivial to keep fzf window open as it's not a native Vim plugin but an external program. What you can do instead is to multi-select matches with `tab` or `shift-tab` (or `alt-a` to select them all) and press enter to put them all at once in the quickfix list of Vim. So using fzf as the first screening process.

What @edi9999 suggested also makes sense. We can even introduce some expiration logic based on timestamp.
