### ISSUE TITLE
Cannot use fzf in gvim

### ISSUE THREAD

**Issue by synic** [junegunn/fzf.vim#207]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

When I type FZF, it opens an xterm window that looks like this: http://d.pr/i/12KUr/2rGJWFE4.  I'm not really sure what it's doing.  I don't want it to open in a different window.

I am using NeoBundle:

```
NeoBundle 'junegunn/fzf.vim'
NeoBundle 'junegunn/fzf'
```

**Comment by synic** [comment]
Nevermind.  It looks like in gvim, it's supposed to open in another terminal.  This is pretty much a deal breaker for me.  I use gvim, but not for the GUI aspects.  I use it because scrolling is faster, color support is better.  When I use fzf, I want it to work exactly the same as it does in the terminal.  Popping up another window for something like this makes little sense to me.

**Comment by junegunn** [comment]
Yeah, since fzf is an external program, there's nothing we can do about it in GVim. Neovim, on the other hand, has its own terminal emulator embedded, so fzf works fine even on GUI version(s) of it. For example https://github.com/equalsraf/neovim-qt

Note that I don't have much experience with GUI versions of Neovim, so I can't really say if they're better than GVim or not.

**Comment by duganchen** [comment]
Wasn't this fixed with #416?
