### ISSUE TITLE
Buffers: switching to a term buffer cannot startinsert

### ISSUE THREAD

**Issue by khalidchawtany** [junegunn/fzf.vim#21]
I have have the following in my **nvimrc**. I want to be able to automatically start in **insert mode** whenever I select a **term buffer** from the `Buffers` command. However, I always end up in normal mode :(

```
   autocmd BufWinEnter,WinEnter term://* startinsert
   tnoremap <c-p><c-b> <c-\><c-n>:Buffers!<cr>
```

**Comment by junegunn** [comment]
I was clueless about this one, but it seems to be related to https://github.com/junegunn/fzf/pull/371 (and 2977f08e8f1aa7476b53ea76f33178b36f8ec113). Maybe I should force-trigger the autocmd. But I'm not completely sure if it - adding `doautocmd` for `BufEnter` - is the right way to handle this. (And you have `BufWinEnter` instead of it!)

**Comment by junegunn** [comment]
Hmm, maybe it's not what it is. I can see that the autocmd is indeed triggered.

```vim
autocmd BufWinEnter,WinEnter term://* echom string(reltime())
```

**Comment by khalidchawtany** [comment]
I have tried a lot of stuff and I have ended up empty handed ;)

**Comment by ipod825** [comment]
autocmd BufEnter * if &ft != 'gitcommit' | silent! lcd %:p:h | endif

This does not works too.
After opening the new buffer with :GFiles (surprisingly, :Files works), pwd remains the same.
I need to switch to another buffer and enter back to get the autocmd triggered.
