### ISSUE TITLE
Cannot open files.

### ISSUE THREAD

**Issue by joshbenham** [junegunn/fzf.vim#24]
Not too sure what I am doing wrong but I installed fzf.vim and it works great.

Then I mapped
`nnoremap <silent> <Leader><Leader> :Files<CR>`
Which also works perfectly.

The problem is that when I choose a file I get this.

Error detected while processing function fzf#vim#files..<SNR>73_fzf..fzf#run..<SNR>38_execute..<SNR>38_callback:
line   27:
Vim(call):E117: Unknown function: s:common_sink
Press ENTER or type command to continue

**Comment by junegunn** [comment]
Hi, it's a known issue on older version of vim, but it should work fine if you upgrade vim.
I know how to workaround the problem; it works if we use autoload functions (`fzf#vim#xxx`) instead of script local functions (`s:xxx`). I haven't decided if I should address the issue or not because of its side effect of exposing implementation details.

**Comment by joshbenham** [comment]
Ok I just updated to 7.4 and it seems like it is working :).

I am going to close this ticket. Thanks :)
