### ISSUE TITLE
Timeout when closing fzf-windows with escape

### ISSUE THREAD

**Issue by yevhen-m** [junegunn/fzf.vim#248]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I have a small timeout when closing fzf-windows hitting escape. `C-c` closes them instantly. Is it possible to get rid of this timeout?

**Comment by junegunn** [comment]
There is 200ms delay which I think is not too bad. Smaller delay may cause problems with escape sequences on some terminals, so I'm reluctant to make it smaller. If you're experiencing longer delay, then you're probably running into, take a look at https://github.com/neovim/neovim/issues/2093.

**Comment by yevhen-m** [comment]
@junegunn I use zsh and I've noticed that delay is similar the terminal (searching history using fzf for example).

**Comment by KevinSjoberg** [comment]
I'm just experiencing this as well. This have never been an issue before, just noticed it today. There must have been a change of some sort?

**Comment by junegunn** [comment]
fzf 0.15.8 changed escape sequence interpreter to ncurses-based implementation. The previous implementation had some fundamental issues and was unreliable on some environments so the change was necessary. A small delay is for reliable consumption of escape sequences and is inevitable due to a limitation of ncurses. Bracketed-paste mode, for example, is not natively supported by ncurses so we have to manually interpret the sequence by reading more characters from TTY in non-blocking mode, but I noticed that switching between blocking and non-blocking mode causes rendering glitches so instead we constantly keep trying using small delays. I'll see if there's a better way to handle this, but for now just use CTRL-C (like me) or use 0.15.7.

**Comment by KevinSjoberg** [comment]
Thanks @junegunn. Awesome explanation, appreciate it. 👍

**Comment by junegunn** [comment]
Okay, I tried to address the issue in https://github.com/junegunn/fzf/commit/43425158f4fbb961d5c365d39664912a7ebf9342 which uses smaller 50ms delay by default and makes it configurable via environment variable $ESCDELAY. If you get a chance, build fzf from source and test it, and let me know if you see any issue.

**Comment by junegunn** [comment]
Escape delay reduced to 50ms in 0.15.9. You can reduce it further by setting $ESCDELAY to a smaller value (in ms), but be careful. I've already observed that using smaller ESCDELAY caused issues with escape sequences (e.g. cursor keys, page up/dn, etc.) in WSL terminal.

**Comment by yevhen-m** [comment]
Perfect, thanks a lot @junegunn.

**Comment by KevinSjoberg** [comment]
@junegunn thanks, really appreciate it. Much more responsive now. 👍

**Comment by ptzz** [comment]
@junegunn Default was increased to 100 in a [seemingly unrelated commit](1448d631a7c72905f62dbb343a8f231a1c3cc52c). Was that indended?
