### ISSUE TITLE
GFiles creates an empty buffer

### ISSUE THREAD

**Issue by 0ax1** [junegunn/fzf.vim#270]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Steps to reproduce:
- au BufEnter * silent! lcd %:p:h is set
- open a file with nvim
- open a new empty tab
- then trigger GFiles, select two entries (with tab) and open them with 'vsplit'

- the split on the right side contains an empty buffer

**Comment by fluffywaffles** [comment]
This is a long-standing issue with FZF -- not that the library cannot support autocd, but that documentation sorely fails to explain the edge cases involved because of assumptions made by FZF in its "load multiple files" code.

It may be helpful to see #321; while it's not exactly the same as your example, it stems from the same problem.

**Comment by 0ax1** [comment]
Thanks for your message.  For me https://github.com/junegunn/fzf.vim/issues/269 fixed the `autocd` issue. The bug described here does not appear if `autocd` is used instead of relying on `au BufEnter * silent! lcd %:p:h`.
