### ISSUE TITLE
Losing focus when trying to toggle Files or Buffers

### ISSUE THREAD

**Issue by CrashyBang** [junegunn/fzf.vim#281]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

So I have the following set up:

```vim
call plug#begin('~/.vim/plugged')

" Fuzzy Finder
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

call plug#end()

function KillRunningFzf()
    for i in filter(range(1, bufnr('$')), 'bufname(v:val) =~# ";#FZF"')
        " Delete buffer by ID
        execute "bw!" . i
    endfor
endfunction

command! -nargs=* ToggleFiles call KillRunningFzf() | Files
command! -nargs=* ToggleBuffers call KillRunningFzf() | Buffers

" Fuzzy finder using fzf
nnoremap <leader>f :ToggleFiles <cr>

" Buffers using fzf
nnoremap <leader>b :ToggleBuffers <cr>
```

The goal is to toggle any existing `fzf` buffers closed if I am trying to open a new `fzf` instance.

I originally posted the issue [here](http://vi.stackexchange.com/questions/10766/toggle-fzf-vim-if-already-open) but thought it may be relevant to other `fzf` users.

When I run `ToggleFiles` or `ToggleBuffers` it either errors with the following:

```
Error running cat "/tmp/nvimPJ9Q3p/4"|"/home/otis/.fzf/bin/fzf"  +m -x --tiebreak=index --header-lines=1 --ansi -d "\t" -n 2,1..2 --prompt="Buf> " --expect=ctrl-v,ctrl-x,ctrl-t > /tmp/
nvimPJ9Q3p/3
```

Or it creates multiple buffers, Or it works as expected and loses focus, I am guessing it is some sort of race condition but I have no idea how to debug.

**Comment by CrashyBang** [comment]
Yeah I ideally would like to just hit `<leader>b` for `:Buffers` realise I need `:Files` and hit `<leader>f` without `CTRL-C`.

Hitting `CTRL-C` that is the problem it is that I don't think to, and then I get the `fzf is already running` error then hit `CTRL-C` then hit `<leader>f`.

Also I believe I have to have the `fzf` buffer focused in order for `CTRL-C` to work whereas I would like to be able to hit `<leader>f` from any buffer.

Does that make sense?

**Comment by junegunn** [comment]
> just hit \<leader\>b 

Since you're using `nnoremap`, you have to switch to normal mode first for that to work, right? Then it's `<C-\><C-n>` followed by `<leader>b`. I don't understand how it's more efficient than `<C-c>` followed by `<leader>b`, which is one less keystroke. Am I missing something? Do you frequently move to other windows while keeping fzf window open? Personally I never do that, since I use regular Vim as my primary editor and it's just not possible there.

Using `tnoremap` might make sense, but in that case it is possible that you may inadvertently close fzf window by typing in `<leader>b`, especially if you use space leader.

Anyway, back to your original question, I believe it's an issue of Neovim implementation and `feedkeys()` might help. See https://github.com/junegunn/fzf/issues/426

**Comment by CrashyBang** [comment]
Hey @junegunn,

I now see what you are saying and I hadn't accounted for having to hit `ESC` to enter normal mode in order for my `<leader>b` to work so yes `CTRL-C` is more effecient :).

Cheers for issue link that actually helps with another issue I am having :).
