### ISSUE TITLE
Tags creation is not async

### ISSUE THREAD

**Issue by sschaef** [junegunn/fzf.vim#29]
I just run `:Tags` in my home directory. It took forever to complete. During that time `neovim` was completely blocked. I had to kill the ctags process manually in order to give control back to `neovim`.

**Comment by junegunn** [comment]
It's beyond the scope of this plugin. There might be a separate plugin that builds tags file in the background, but when you run `:Tags` command, the file should be ready and it makes more sense to build it synchronously. I suppose your case was accidental, right? Since it's hard to determine if the current directory is the right directory to build tags files from, maybe it's just better for `:Tags` command not to build tags file and simply fail with an error message.

**Comment by sschaef** [comment]
I would indeed prefer if it fails with an error message. Seems to be the better solution than to block for a long time in the worst case.
