### ISSUE TITLE
CTRL-E doesn't work, when History: command view activated

### ISSUE THREAD

**Issue by vbauerster** [junegunn/fzf.vim#313]
- Category
    - [x] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Pressing CTRL-E to edit, produces a beep without command pasted to command prompt.
Pressing enter on any item, doesn't execute a command as expected, but command prompt gets populated with `:execute g:__fzf_command`.
I've tried to test with
`nvim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw/vimrc)`
as advised, and it works. So looks like it is problem in my config or conflict with another plugin.

Here is my neovim [config](https://github.com/vbauerster/dotfiles/blob/master/config/nvim/init.vim) and [plugins](https://github.com/vbauerster/dotfiles/blob/master/config/nvim/config/nvimrc.plug) I use. Also my default shell is zsh.

How can I debug or troubleshot the problem? Any help appreciated, thanks in advance.

**Comment by vbauerster** [comment]
Let me point out, that `History/` command has same CTRL-E shortcut, which works as expected.

**Comment by vbauerster** [comment]
I found what was the problem. After removing following mappings, the problem is gone.
```
nnoremap ; :
nnoremap : ;
```

**Comment by gdzwrk** [comment]
I've run into this as well. Is there any way to modify the CTRL-E shortcut behavior to account for this (relatively common, I think) mapping?  I've found a workaround, which is to change my mapping to
````
nnoremap ; :
nmap : ;
```
in order to allow the ':' character to map to ';' which then actually invokes the ex command line.
This breaks my ability to use ':' to search for the next occurrence with fF/tT- admittedly I don't use it much, but it would be nice to have it back. I'd even be happy with a manual edit to the vimscript...

**Comment by junegunn** [comment]
Do you have the latest version? See https://github.com/junegunn/fzf.vim/commit/7bf940d261795b5164bc854f37a121fcca927941

**Comment by gdzwrk** [comment]
Yes, I think so:
```
➜  fzf.vim git:(master) git rev-parse master
b31512e2a2d062ee4b6eb38864594c83f1ad2c2f
```
I can't find that specific commit in the git rev-list.. it only shows the one I listed above. 
I'm using FZF on zsh, with vim 8.0 on WSL-Ubuntu on Win 10.
