### ISSUE TITLE
my effort into replacing ctags jump with fzf.vim's :Tags command

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [junegunn/fzf.vim#323]
tags jump in vim is not as good as IDE. But fzf makes it better.
In :Tags and :BTags, we search accuracy word under cursor most time. so i config this:
```vim
nnoremap <leader>d :call fzf#vim#tags("'" . expand('<cword>'))<CR>
```
and if there is only one match, most time it is, jumping to that tag position directly is better than showing a fzf window and press enter to jump. Thanks to your wonderful fzf configuration, I change 2 lines in fzf.vim ,simplely add  `--select-1 --exit-0` option.
<img width="1271" alt="screen shot 2017-02-26 at 9 57 40 am" src="https://cloud.githubusercontent.com/assets/2133400/23336411/81a0652a-fc0a-11e6-9627-efe61aea06c5.png">
<img width="1072" alt="screen shot 2017-02-26 at 9 57 55 am" src="https://cloud.githubusercontent.com/assets/2133400/23336413/8d803442-fc0a-11e6-92aa-be4236ceda45.png">
now it works very well. 
BTW, why there is '--reverse' option on btags but tags has not?

**Comment by junegunn** [comment]
Thanks for sharing.

You don't have to change the source code of fzf.vim since you can pass arbitrary options to the autoload function like follows.

```vim
nnoremap <leader>d :call fzf#vim#tags(expand('<cword>'), {'options': '--exact --select-1 --exit-0'})<CR>
```

> BTW, why there is '--reverse' option on btags but tags has not?

To show the tags in the file in the order they appear in the file, top to bottom. The same goes for`BLines` and `Lines`. You can pass `--no-reverse` to unset the option.

**Comment by PezCoder** [comment]
This is exactly what i wanted & works find, except for the fact that after navigating it's not pushed in the stack i.e I'm not able to come back using `<C-t>`
I understand `<C-o>` is an alternative but that's only useful if we're not navigating in the landing position, it just fills up while `<C-t>` remains the same in this case.

Is it possible to push it in that stack somehow ?

**Comment by PezCoder** [comment]
Actually find an issue open regarding the same.
https://github.com/junegunn/fzf.vim/issues/240

**Comment by hasufell** [comment]
I tried this too. Not really usable: 

1. When jumping to a tag, I don't really get to the actual tag, it's very buggy. It seems I just get to the *file*, not the line (or just stay at the current cursor position if the tag is in the same file).
2. the search is not exact, even with `--exact` and I get pretty unrelated finds

**Comment by asgeirrr** [comment]
You can get more precise results with

```vim
nnoremap <leader>d :call fzf#vim#tags('^' . expand('<cword>'), {'options': '--exact --select-1 --exit-0 +i'})<CR>
```
This matches tags starting with the word under cursor but I haven't found a simple way to match the end of the tag since the line in fzf contains path the the tag as well. 

@hasufell consider Vim's built-in g<C-]> that does exactly what you want, it's just not as pretty as fzf.
