### ISSUE TITLE
Ag command double dot

### ISSUE THREAD

**Issue by nbeydoon** [junegunn/fzf.vim#348]
- Category
    - [ ] Question
    - [x ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x ] Neovim

Hi, with the command Ag when I try to open a path including ':' the pass stop before the ':'.

Ex '/Users/nbeydoon/works/toto:tata' try to open '/Users/nbeydoon/works/toto' thus give me a File not found

**Comment by junegunn** [comment]
Hmm, I'm not sure if there's a robust solution to the problem. The output of ag is inherently ambiguous when the file name contains colons. For example, given the following line, can you tell where the file name ends?

```
foo:1:2:3:4:5:6:7:bar
```

The only way to tell is to inspect ANSI color codes. But it's not guaranteed to work since ANSI colors can be turned off.

I'll close this as I can't think of a fine solution and I believe that file names with colons are rare, but thanks for the report.
