### ISSUE TITLE
Lines and BLines preview functionality

### ISSUE THREAD

**Issue by blkwtkns** [junegunn/fzf.vim#374]
- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

I was a little curious about having the preview functionality extend to the :Lines command, and a fellow redditor, /u/bassforte95,  gave me a great a great patch to implement the functionality, which you can reference here: https://www.reddit.com/r/vim/comments/6awwk5/configuring_fzf_preview/?ref=share&ref_source=link

For my system I did have to add an extra line the in preview.rb file to make it function (ref in linked reddit thread), although I didn't try to extend the logic to the .sh file. It also doesn't completely work for BLines, the preview function tries to take the whole string result as a file name when attempting to use the preview function. Anyways, I thought I'd throw /u/bassforte95's logic your way and get your thoughts on previews for :Lines, and :BLines as well. I'm loving the plugin otherwise, thanks!

**Comment by junegunn** [comment]
Preview scripts expect a certain format (`filename[:line[:col]][...]`) so yeah, they won't work with Lines or BLines, and I can't think of an easy way to fix that.

1. I like the fact that Lines command shortens the file names, as they can be quite lengthy and take up much of the screen estate.
2. Also, printing file name on each and every line in BLines output just to make the preview script work doesn't seem to make much sense. Instead of doing that, we should consider building up `--preview` argument to pass the filename directly to the preview script.

**Comment by blkwtkns** [comment]
That's what I was hoping for, and this would enable the preview function to not rely on display information. 

Even so, I do have the Lines preview working on my fork, and it's not so bad, but I too prefer the truncated display. BLines has proved a bit more difficult, and I kind of got fed up with it and figured that the preview function itself would be better to work on. If I get some time to make an improvement on it I'll update you. Thanks for your input!

**Comment by balta2ar** [comment]
@junegunn Is there an easy way to add preview for Tags command?

**Comment by junegunn** [comment]
@balta2ar Nope. A tags file doesn't necessarily have line numbers.

**Comment by joaqo** [comment]
@blkwtkns hey I also was looking for a preview pane on the BLines command, as I am currently using it to substitute `/` in vim. Would you mind me asking if you continued to work on it? Thanks!

**Comment by AnakinXL** [comment]
For the short term, I have found a workaround which piggybacks on grep view (using `ripgrep`) that kinda works for me..... With the biggest downside of **not having syntax highlighting** on my preview code (but still better than none 😂 )

The code is basically copied from the `:Rg` (ripgrep) code with 2 differences: 1) specifying the current filename, and 2) a extra `--with-filename` flag, like this:

```
command! -bang -nargs=* LinesWithPreview
    \ call fzf#vim#grep(
    \   'rg --with-filename --column --line-number --no-heading --color=always --smart-case . '.fnameescape(expand('%')), 1,
    \   fzf#vim#with_preview('up:50%', '?'),
    \   1)
nnoremap H :LinesWithPreview<CR>
```

And the result looks just like a grep view:
<img width="855" alt="screenshot" src="https://user-images.githubusercontent.com/133680/54864617-f36ae900-4d16-11e9-80f3-aec327d10601.png">

It's probably not for everyone, but hopefully this provides some new ideas... :)

**Comment by ssh352** [comment]
@AnakinXL LinesWithPreview works great, could you advise how to make a similar BlinesWithPreview?

**Comment by oessaid** [comment]
> @AnakinXL LinesWithPreview works great, could you advise how to make a similar BlinesWithPreview?

For inspiration, here's what I use as a custom BLines:
```vim
command! -bang -nargs=* CustomBLines
    \ call fzf#vim#grep(
    \   'rg --with-filename --column --line-number --no-heading --smart-case . '.fnameescape(expand('%:p')), 1,
    \   fzf#vim#with_preview({'options': '--keep-right --delimiter : --nth 4.. --preview "bat -p --color always {}"'}, 'right:60%' ))
nnoremap <leader>/ :CustomBLines<Cr>
```
I alleviate not being able to get rid of file names in the results (as fzf seems to need the file name) by using `--keep-right`, which at least prioritizes showing the results instead of the file name when it's very long. You'll need `bat` for this, if you want syntax highlighting.

Also, this displays in a floating window because of:
```vim
let g:fzf_layout = { 'window': { 'width': 0.6, 'height': 0.6 }}
```
It looks like this:
![image](https://user-images.githubusercontent.com/35626945/96443043-4b781300-120c-11eb-80e3-a08bf89c1df0.png)

**Comment by fedoranvar** [comment]
Updated script above.
And commented line for future `Lines` preview functionality.
Also this script can handle query input like `:BLines <word-to-search>`
```
command! -bang -nargs=* BLines
    \ call fzf#vim#grep(
    \   'rg --with-filename --column --line-number --no-heading --smart-case . '.fnameescape(expand('%:p')), 1,
    \   fzf#vim#with_preview({'options': '--layout reverse --query '.shellescape(<q-args>).' --with-nth=4.. --delimiter=":"'}, 'right:50%'))
    " \   fzf#vim#with_preview({'options': '--layout reverse  --with-nth=-1.. --delimiter="/"'}, 'right:50%'))
```
![image](https://user-images.githubusercontent.com/52028706/98600921-1ab56600-2300-11eb-9865-87dfd164e431.png)

**Comment by jdsutherland** [comment]
@AnakinXL isn't `LinesWithPreview` essentially `BLines`? It seems to only use the current buffer rather than all open buffers (like `Lines`).

**Comment by fabriziobertoglio1987** [comment]
> @AnakinXL isn't `LinesWithPreview` essentially `BLines`? It seems to only use the current buffer rather than all open buffers (like `Lines`). The comments read as if `LinesWithPreview` is analogous to `Lines`, and then there are more recent posts listing a preview for `BLines`, hence the confusion.

yes. I also find this as big weakness as I would prefer the command to search the entire Buffer and not only the current file. All those commands use `rg` to search in 1 file 

and they don't use BLines which in some scenarios may be more useful

**Comment by fabriziobertoglio1987** [comment]
Hello @junegunn 

I'm Fabrizio Bertoglio and since 1 year I contribute to many OpenSource project. I really like your project and I'm considering contributing in the future to this project. I would need some help now in troubleshooting this issue and in the future I will pay back your favour with OpenSource contributions.

after using this I found some serious weakness in this functionality.

Thanks a lot 🙏 

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

TEST SCENARIO
- I use normal fzf function to search for a result. I navigate to that result, then I go back with ctrl+o

RESULT
- I navigate to the previous result with ctrl+o

<video src="https://user-images.githubusercontent.com/24992535/126885195-d93886ab-e790-47b0-aff8-0e6e2e5691ce.mov" width="700" height="" />

</p>
</details>

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

TEST SCENARIO
- I use the above included fzf function to search for a result in the same file. I navigate to that result, then I go back with ctrl+o

RESULT
- I don't navigate to the previous result, but to the original position before using the fzf function above included

<video src="https://user-images.githubusercontent.com/24992535/126885321-a29faf97-0dbe-4f9e-9e1c-624fd35301bd.mov" width="700" height="" />

</p>
</details>

**Comment by fabOnReact** [comment]
command FzfPreviewBufferLinesRpc  from plugin https://github.com/yuki-yano/fzf-preview.vim displays Lines with preview. From the entire buffer, not only the current buffer 🥳
