### ISSUE TITLE
Ripgrep interactive mode is extremely slow

### ISSUE THREAD

**Issue by hahuang65** [junegunn/fzf.vim#488]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim

Using

```
map <leader>/ :Rg<Cr>

command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --hidden --fixed-strings --follow --ignore-case --no-ignore --glob "!.git/*" --color=always '.shellescape(<q-args>), 1,
  \   <bang>0 ? fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'up:60%')
  \           : fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'right:50%:hidden', '?'),
  \   <bang>0)
```

vs.

```
map <leader>/ :Ag<Cr>
```

has some interesting issues:
1) Using `:Rg <term> <CR>` is LIGHTNING fast.
2) Using `<leader>/` to use `:Rg` in interactive mode is 10 times slower than `:Ag` in interactive mode.

Is there any reason why interactive mode for ripgrep is much slower than the_silver_searcher? Is it the way I configured `:Rg`?

**Comment by hahuang65** [comment]
Attaching a small gif that shows what I mean. First I do a straight `:Rg` search which is fast enough. Then I show the comparison between the interactive modes of `:Rg` and `:Ag`
The `:Ag` runs shows results and scans them MUCH faster than `:Rg`.
![demo](https://user-images.githubusercontent.com/280972/32252764-4865a7e0-be54-11e7-826f-22f0d89ef6bd.gif)

**Comment by junegunn** [comment]
No idea what's going on there. Make sure to install the latest version of ripgrep (0.7.1).

**Comment by hahuang65** [comment]
Yeah, I've got the latest installed. Do you have any tips for me to debug this, or is this something I just need to live with?

Is this something I need to file with ripgrep?

**Comment by junegunn** [comment]
Since it's not an issue of fzf, I can't really help. If ag works great, why don't you just use it? It's sufficiently fast for most use cases. By the way, I'm not sure starting ag or rg without any keyword is a good strategy since they are much more efficient for searching inside files and fzf will have to need a lot of memory to keep every line in memory.

These are the binding I use with ag.

https://github.com/junegunn/dotfiles/blob/255248256762bd8b1f997da8c786db57975979cb/vimrc#L1646

**Comment by hahuang65** [comment]
Yeah, I'll do that. Thanks for taking a look at this. Appreciate all  your work!

**Comment by Alok** [comment]
@hahuang65  The `color=always` may have something to do with it, because I get instant results with `color=never` and slow ones with color always.

**Comment by hahuang65** [comment]
Oh good tip. I'll try that. Thanks

**Comment by unphased** [comment]
So like, I'm not completely sure what's going on, but:

From the looks of it, `fzf#vim#grep` pipes the output of the command provided to feed straight into fzf, which keeps it in-process. E.g. in my `~/.vim` with 105MB of content (i have many plugins), about 66MB of code content (including the filenames and line numbers) actually gets fed into the `fzf` process which goes ahead and handles your fuzzy matching filtering and so forth. 

What this means is that your `rg` command gets run ONCE. In fact what you have going on is (and this is where I'm not sure what the hell is going on with `<q-args>` and such) **`rg` is being used to produce the entire set of file content in a tabulated list of filename and line number and line content**. 

You may recall that `rg` is fast at searching files. We're giving it the task of dumping ALL content from matching files. 

And so as it turns out, this isn't its strong suit, and system `grep` is quite better at producing a faster stream when matching with `-vnIr "^$"` which essentially just drops any empty lines (`-v` inverts).

Anywho, unless you have some particular special reason to use your `rg` config that knows exactly which files are the files that you want to scan, then it looks like it ain't the best tool for this job.

**Comment by unphased** [comment]
So I wrote up this whole thing but i got ahead of myself so i'm rewriting my comment. 

It looks like ag and rg have quite different methods of outputting content, and rg is much slower. rg is quite more speedy at doing actual searching however. But the way you're using this is such that hundreds of thousands of lines (no doubt something like nearly every nonempty line getting matched and sent into FZF for fuzzy matching) are produced, so rg happens to be sluggish in comparison to ag and grep. I've noticed this.

**Comment by hahuang65** [comment]
Thanks for doing the investigation and explaining it to me. It really helps!

**Comment by BurntSushi** [comment]
@unphased Can you provide a reproducible test case outside of fzf and contribute it to ripgrep so that we can fix it? A bug was already filed but it lacks details: https://github.com/BurntSushi/ripgrep/issues/696

**Comment by unphased** [comment]
Further investigation indicates that `rg` output is never slow, but nevertheless, in vim-fzf, and **only** when outputting color, the performance is reduced. The reason is unclear at this time. 

The quick workaround for OP and others troubled by the behavior is to configure an `rg` command for fzf (when used in vim) without color.
