### ISSUE TITLE
Can this take into account the current file?

### ISSUE THREAD

**Issue by svenstaro** [junegunn/fzf.vim#492]
- Category
    - [x] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hey, so I was wondering whether fzf.vim can take into account the current file name. When you start searching, starting from nothing is a worse guess than starting from the current file name most of the time I think.

Consider a C program where you might want to switch between `.c` and `.h` files. Or consider a Python application where there is `my_module.py` and somewhere else in the tree there is `test_my_module.py`. It would be really neat if this plugin would take that into account and maybe it does but I don't know how to make it to that.

If it doesn't do that, consider this a suggestion.

**Comment by vimeitor** [comment]
To expand on this with another example: suppose we are at a given directory editing a file called **file.c**. If in this same directory there's a file called **another.c**, when typing "an", it should always match **another.c** before any other file in any other directory starting with "an". In other words, files in the current directory should get preference. We could generalize this and say that the closer the directory of a file is to our file, the higher the ranking should be if they start with the same letters. I think that would be a pretty good improvement, and it's what matchers like [cpsm](https://github.com/nixprime/cpsm) do.

**Comment by junegunn** [comment]
fzf is a general-purpose text filter that works with any kind of input rather than just a file selector that is optimized for file paths, and implementing a special ranking algorithm for a certain type of input is a non-goal.

Having said that, there are ways to implement the ideas you mentioned.

1. Find a command or write a script that lists files under the current directory except a certain file. Let's say that it's called `find-except <ARGUMENT>`, and all you have to do is to use it as the source.

```vim
call fzf#run(fzf#wrap({'source': 'find-except '.shellescape(expand('%'))}))
```

2. Find a command or write a script that lists files in a specific order you want (e.g. files in the current directory should appear first). Let's say it's `find-in-some-order`. You can specify how fzf sorts the matches of the same score ("tie") using `--tiebreak` option. See `man fzf` for details, but in this case, what you want is `index`.

```vim
call fzf#run(fzf#wrap({'source': 'find-in-some-order', 'options': '--tiebreak=index'}))
```

Check out https://github.com/junegunn/fzf/blob/master/README-VIM.md if you want to learn more about the options.

**Comment by svenstaro** [comment]
Thanks @junegunn, though both of these methods sound like I wouldn't get a match quite as good as with cpsm. I'll stick to that for now.
