### ISSUE TITLE
search and replace in project?

### ISSUE THREAD

**Issue by lhyaax** [junegunn/fzf.vim#528]
How to search and replace in project?
:Ag   can search file , and then ?

**Comment by trevordmiller** [comment]
Assuming you are using Vim 7.4+, you can use `cdo` and `cfdo` to run commands over items in the quickfix list natively. `:Ag` from this plugin does let you populate the quickfix list - so the whole flow is this:

Plugin specific:
- `:Ag foo` then `enter`
- `alt-a` to select items (if using iTerm2 on macOS, [you need `Esc+` turned on for alt/option keys](https://github.com/junegunn/fzf.vim/issues/54#issuecomment-350417085))
- `enter` to populate quickfix list with selected items

Native:
- Once quickfix list is populated, you can  run a file substitute command then save every file in the quickfix list like this:
`:cfdo %s/foo/bar/g | :w`

This seems a bit complicated, but it's actually really powerful because you can run any other command, not just substitute. For example. you could run a macro on each matching quickfix item like this:

`:cdo normal @q`

etc.

More info on `cdo` and `cfdo`: https://robots.thoughtbot.com/lists-vim-and-you#from-inside-of-vim

Related: https://github.com/junegunn/fzf.vim/issues/586

**Comment by dakom** [comment]
Can you please suggest how to do ALT-A in xfce-terminal? (it selects the terminal menu by default)

**Comment by rakshans1** [comment]
Hi
I am trying to implement search and replace in the project with new [fzf change reload ](https://github.com/junegunn/fzf.vim#example-advanced-ripgrep-integration)

I want to achieve  following features
1. Start Rg with the current word below the cursor
2. Update if the query is changed
3. Selection with alt-a / tab will automatically be added to quickfix list by fzf
4. Run `:cfdo %s/newquery/ /g | :w` with new query

https://github.com/rakshans1/dotfiles/blob/master/config/nvim/plugin/fzf.vim#L82

I am able to get till step 3 but not able to retrieve new search query for substitution

**Comment by partounian** [comment]
ALT-A doesn't work for me using neovim, oh-my-zsh, and iTerm2. I have set the Option key to send Esc+ as recommended. Anyone else having this issue?

**Comment by junegunn** [comment]
@partounian I needed to put these in my Vim configuration file:

```vim
if has('nvim')
  tnoremap <a-a> <esc>a
  tnoremap <a-b> <esc>b
  tnoremap <a-d> <esc>d
  tnoremap <a-f> <esc>f
endif
```

**Comment by sheerun** [comment]
it doesn't really solve the issue as all patterns in quicklst files are replaced, while I'd expect only selected lines are replaced

**Comment by sheerun** [comment]
Following is the correct command:

```
:cdo s/foo/bar/ | :w
```

**Comment by sheerun** [comment]
Does anyone know how to get last searched phrase from fzf? something like `/` register. I need it so I can pass it as an argument to the `:cdo`

**Comment by MeNsaaH** [comment]
@MushiTheMoshi  did you figure this out?

**Comment by MushiTheMoshi** [comment]
thanks!
