### ISSUE TITLE
Toggle fullscreen

### ISSUE THREAD

**Issue by AuditeMarlow** [junegunn/fzf.vim#613]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hi junegunn, thanks for your great work on fzf as a whole. Now I was wondering, is there a way to toggle back and forth between fullscreen and not fullscreen?

**Comment by junegunn** [comment]
If you're on tmux, you can set `let g:fzf_prefer_tmux = 1` and fzf will start in a tmux split pane, which you can zoom in and out using a tmux key binding. Otherwise, it's not possible.

The experience with the above option will not be ideal on Neovim. It works, but the main pane becomes blank when fzf pane is started.

**Comment by AuditeMarlow** [comment]
Great, thanks!
