### ISSUE TITLE
Could BTags maintain symbol order?

### ISSUE THREAD

**Issue by demon386** [junegunn/fzf.vim#72]
I found that BTags doesn't maintain the symbol order in this buffer. (e.g. `ttt` appears before `aaa` in the buffer, but BTags doesn't keep this order).

Is it possible to keep this order? So that BTags has the extra benefit for getting an overview with the buffer.

**Comment by junegunn** [comment]
BTags simply uses the output of `ctags` command, and I believe that it respects the original order of symbols. I think you got the impression that the order is not maintained because fzf displays the list in bottom-up fashion. So if you add `--reverse` to your `$FZF_DEFAULT_OPTS`, you'll notice that the symbols are listed as expected.

The question is if we should apply `--reverse` option to `BTags` by default like `Lines` command.

**Comment by demon386** [comment]
Oh you are right. Do you think making '--reverse' the default option for `BTags` makes sense?

**Comment by junegunn** [comment]
Yeah, let's do this.
