### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by moisturizer** [junegunn/fzf.vim#73]
###### I have the following in my init.vim:
autocmd VimEnter * command! Buffers
      \ call fzf#vim#buffers({'down': '40%', 'options': '--no-color'})
autocmd VimEnter * command! History
      \ call fzf#vim#history({'down': '40%', 'options': '--no-color'})
autocmd VimEnter * command! Files
      \ call fzf#vim#files({'down': '40%', 'options': '--no-color'})

###### When I invoke the :Files command I get the following error, :Buffers and :History work fine
Error detected while processing function fzf#vim#files:
line    3:
E731: using Dictionary as a String
Invalid directory

###### Is it currently possible to have fzf.vim use the terminal's colors? (or is there an example of how to customize the colors)

**Comment by junegunn** [comment]
The API is intentionally left undocumented, since they are not fixed. But anyway, the first argument to `fzf#vim#files` is the path to start traversal. See `plugin/fzf.vim` for the details.

Looks like you want to apply `--no-color` uniformly to the commands, if that's the case, it would be simpler to set up `$FZF_DEFAULT_OPTS`. It can be set either in your shell configuration file (`export FZF_DEFAULT_OPTS='--no-color'` or in your init.vim (`let $FZF_DEFAULT_OPTS = '--no-color'`)

For advanced customization of colors, refer to https://github.com/junegunn/fzf/wiki/Color-schemes.
