### ISSUE TITLE
Suggestion: Add possibility to restart/change root for :Files in parent directory without exiting

### ISSUE THREAD

**Issue by ghost** [junegunn/fzf.vim#754]
- Category
    - [ ] Question
    - [ ] Bug
    - [ X] Suggestion
- OS
    - [ X] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ X] Vim
    - [ ] Neovim

When opening :FZF or :Files I often find myself in one directory "too low" and would want to change to parent directory. Now I need to exit and restart with parent dir as arg.
A nice feature would be to be able press for example DEL or backspace when at the root prompt to restart the search in the parent directory without having to exit. I haven't found any such possibilities when skimming through the documentation.

**Comment by Millani** [comment]
This would be a truly great feature. Really hopes it get considered.

**Comment by junegunn** [comment]
I don't really need the feature since I always stay on the project root directory. But I believe you can try implementing the scheme in your Vim configuration file.

Start with https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfrun and https://github.com/junegunn/fzf/wiki/Examples-(vim).

If you're not familiar with Vimscript, I recommend that you read through http://learnvimscriptthehardway.stevelosh.com/

**Comment by losnappas** [comment]
You can sort of create this with a config like this
```vim
let g:fzf_action = {'alt-c': "call fzf#run(fzf#wrap({ 'dir': '..' }))",
\ 'ctrl-t': 'tab split',
\ 'ctrl-x': 'split',
\ 'ctrl-v': 'vsplit' }
```
and now, as long as the cmd line is empty (c-u and c-y will help there), alt-c will take you up one dir, but it throws a lot of errors because this isn't what the fzf_action is for since it gives the current filename as an argument to the command. I tried silencing it with `silent! call....` but for some reason some of the keybinds get messed up (at least enter and shift-tab).

If there was an option to ignore the filename argument in the command it would work great (probably). I realize this is taking the fzf_action thingy a bit off the rails.

`nmap <m-c> :call fzf#run(fzf#wrap({ 'dir': '..' }))` did nothing.

**Comment by kongluoxing** [comment]
> You can sort of create this with a config like this
> 
> ```viml
> let g:fzf_action = {'alt-c': "call fzf#run(fzf#wrap({ 'dir': '..' }))",
> \ 'ctrl-t': 'tab split',
> \ 'ctrl-x': 'split',
> \ 'ctrl-v': 'vsplit' }
> ```
> 
> and now, as long as the cmd line is empty (c-u and c-y will help there), alt-c will take you up one dir, but it throws a lot of errors because this isn't what the fzf_action is for since it gives the current filename as an argument to the command. I tried silencing it with `silent! call....` but for some reason some of the keybinds get messed up (at least enter and shift-tab).
> 
> If there was an option to ignore the filename argument in the command it would work great (probably). I realize this is taking the fzf_action thingy a bit off the rails.
> 
> `nmap <m-c> :call fzf#run(fzf#wrap({ 'dir': '..' }))` did nothing.

I found a workaround, just append a " that make vim treat following arguments as comment
```
let g:fzf_action = {'alt-c': "call fzf#run(fzf#wrap({ 'dir': '..' }))\"",
\ 'ctrl-t': 'tab split',
\ 'ctrl-x': 'split',
\ 'ctrl-v': 'vsplit' }
```

**Comment by ptn** [comment]
I solved a specific use case of this. When I want to do this, it's because I'm in a `__tests__` or `__stories__` directory, and what I really want to do is limit my search one level up. So I wrote this:

```
function! NeighborFiles(dir, something)
  let l:abs_path = expand('%:h')
  let l:search_dir = fnamemodify(l:abs_path, ':p')

  let l:dirname = fnamemodify(l:abs_path, ':t')
  if l:dirname == '__tests__' || l:dirname == '__stories__'
    let l:search_dir = fnamemodify(l:abs_path.'/../', ':p')
  endif
  call fzf#vim#files(l:search_dir, a:something)
endfunction
command! -bang -nargs=? -complete=dir NeighborFiles call NeighborFiles(<q-args>, <bang>0)
```

Not exactly what you wanted, but hopefully you can use it, maybe as a starting point.
