### ISSUE TITLE
use fd for filenames search

### ISSUE THREAD

**Issue by MeisterTea** [junegunn/fzf.vim#757]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Is it possible to call [fd](https://github.com/sharkdp/fd) to search for files ? 
I am using 

```
command! -bang -nargs=? -complete=dir Fd
  \ call fzf#vim#grep(
  \   'fd '.shellescape(<q-args>),
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview('right:50%:hidden', '?'),
  \   <bang>0)
```
but I am getting this error when selecting the file I want

> Vim(let):E728: Using a Dictionary as a Number

**Comment by badfilms** [comment]
`grep`/`rg`/`ag` is used to search the contents of files, which `fd` is not designed to do, so that code won't simply plug-and-play with `fd`. What you are probably looking for is setting the environmental variable `FZF_DEFAULT_COMMAND`. There is an example provided in the fzf repo:

`export FZF_DEFAULT_COMMAND='fd --type f'`

This way you can use the provided `:Files` command, and use the examples in this repo to add the preview window if you'd like.
