### ISSUE TITLE
Keyboard shortcut to copy file name of selected file

### ISSUE THREAD

**Issue by nickjj** [junegunn/fzf.vim#772]
- Category
      - [ ] Question
      - [ ] Bug
      - [ x] Suggestion

Here's what I would really love to be able to do:

1. Invoke `:Files` like usual
2. Search for a specific file
3. Highlight the file in the list but don't open it
4. Hit a hotkey (let's say CTRL + Y) and it will copy the highlighted file name

Right now you need to find the file, open it, and then run some Vim command to copy the file name, close the buffer and go back to the buffer you really want to paste the file name in.

This use case comes up all the time for me when blogging with Jekyll. You can link to your own posts by inserting`{% post_url <file name> %}`. So whenever I want to cross link a post in my blog it takes a long time to search for the post and copy its file name to my clipboard.

Is there any way to set this up now, and if not, would you be interested in adding `CTRL + Y` as a feature?

**Comment by junegunn** [comment]
## Short answer

`:Files` command uses the default sink function for file paths, which understands `g:fzf_action`. So here is a simple solution.

```vim
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit',
  \ 'ctrl-y': {lines -> setreg('*', join(lines, "\n"))}}
```

## Under the hood

You can stop reading here if you are not interested in the details. I'm going to explain what's going on under the hood for those who are curious.

Before we start, I suggest that you read through [README-VIM](https://github.com/junegunn/fzf/blob/master/README-VIM.md). You need to know about two functions: `fzf#run` and `fzf#wrap`.

Let's first implement a simple command that copies the selected path to the register using `fzf#run` function. The default "source" for fzf is the list of files under the current directory, or the output of the command specified in `$FZF_DEFAULT_COMMAND`, so we only need to define the "sink" function that will process the final output from fzf process.

```vim
" Sink function defined using lambda expression of Vim 8
command! YankFile call fzf#run({'sink': {line -> setreg('*', line)}})
```

If you want to select multiple files with tab and shift-tab, you need to pass `--multi` option to fzf, and use `sink*` function instead of `sink` function (asterisk meaning that it processes multiple lines instead of one).

```vim
command! YankFile call fzf#run({'options': '--multi', 'sink*': {lines -> setreg('*', join(lines, "\n"))}})
```

You may have noticed by now that the above command opens in full screen unlike `Files` command, and it does not respect global configuration variables such as `g:fzf_layout` and `g:fzf_colors`. That's because `fzf#run` doesn't know about them. Those variables are interpreted by `fzf#wrap` which takes an options dictionary and returns a copy of it with some additional options.

- https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfwrap

By simply "wrapping" your options with `fzf#wrap`, your command now understands the global settings.

```vim
command! YankFile call fzf#run(fzf#wrap({'options': '--multi', 'sink*': {lines -> setreg('*', join(lines, "\n"))}}))
```

_Let's just assume that there is no `:Files` command and we have to implement our own version of it._

`fzf#wrap` generates a generic sink function for file paths if a custom sink is not provided (`sink` or `sink*`). So implementing a simple file opener is trivial.

```vim
" Our new version of Files. Optionally takes a directory to start search from.
command! -nargs=? -complete=dir Files call fzf#run(fzf#wrap({'dir': <q-args>}))
```

The generic sink function understands `g:fzf_action` so it can open a file in a new tab or in a new split when the user presses `CTRL-T` or `CTRL-V` instead of `Enter`. So how does fzf know which key the user pressed to select an entry? Using `--expect` option.

```sh
fzf --expect=ctrl-t,ctrl-v,ctrl-x
```

When you hit one of the keys, you'll notice that the first line of the output becomes the name of the key. The generic sink function will read the first line and act accordingly.

_Let's again assume that the generic sink function does not support `g:fzf_action`, so there's no direct way to extend its functionality._

We want fzf to "expect" CTRL-Y as well.

```sh
fzf --expect=ctrl-t,ctrl-v,ctrl-x --expect=ctrl-y
```

So we need to add `--expect=ctrl-y` to `options`.

And we do not want to rewrite the sink function from scratch. We will check the first line of the output, and copy the selected lines to the register if it's `ctrl-y`, otherwise fallback to the original sink function.

```vim
function! MyFiles(dir)
  let dict = fzf#wrap({'dir': a:dir, 'options': '--multi --expect=ctrl-y'})
  let dict['orig'] = dict['sink*']
  function! dict['sink*'](lines)
    if get(a:lines, 0, '') == 'ctrl-y'
      call setreg('*', join(a:lines[1:], "\n"))
    else
      call self.orig(a:lines)
    endif
  endfunction

  call fzf#run(dict)
endfunction

command! -nargs=? -complete=dir Files call MyFiles(<q-args>)
```

**Comment by nickjj** [comment]
Thanks a lot for such a detailed answer.

For clarity, if I define this:
`command! YankFile call fzf#run(fzf#wrap({'options': '--multi', 'sink*': {lines -> setreg('*', join(lines, "\n"))}}))`

Does that mean I can set this:

```viml
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit',
  \ 'ctrl-y': 'YankFile'}
```

And now the benefits over the short answer is it supports multiple files being copied?

**Comment by mars90226** [comment]
Your setting is wrong in two ways:

1. What your setting does is that when you press `ctrl-y` in fzf buffer, it will try to execute `:YankFile [files]`. Then vim will find that `YankFile` doesn't take an argument and complain about it. And, 
2. The `YankFile` command will open up a fzf buffer for you to yank the selected files, which is probably not what you want. You can just use the short answer from junegunn, that's the simplest way to implement what you want.

**Comment by markwu** [comment]
@junegunn  Thanks for such default explanation, now I know how to customize my own fzf hot key.

**Comment by gandalf0151** [comment]
@junegunn  How can I extend this functionality to yank the whole file into clipboard instead of just the filename ?
Kindly provide guidance as I'm unable to understand how those are working

**Comment by gandalf0151** [comment]
I was able to implement this using fzf_action
```    \ 'ctrl-y': ':%w !xclip -selection clipboard', ```
Thanks for this wonderful tool

**Comment by RhvdG** [comment]
> `:Files` command uses the default sink function for file paths, which understands `g:fzf_action`. So here is a simple solution.

I am guessing that the :Rg command _doesn't_ use the default sink function (I have no idea what these words mean, frankly), because the shortcut doesn't yank the filename there. Is there any chance this might be implemented? It would be useful (for instance) in conjunction with wiki.vim.

**Comment by pascualpobil** [comment]
Hi everyone, I'm a pretty noob vim user and I'm really interested in applying this solution into my workflow.

I'm obviously wrong, but I'll tell you what I did. I added the short answer snippet to my init.vim expecting that when I pressed Ctrl-y the name of the selected file would be yanked to my clipboard and I'd be able to paste it right away with p.

Is that how this is supposed to work? It's not working for me so I'm guessing there is something I have to do that I'm missing. Any help would be really appreciated. Cheers!

**Comment by apiwat-chantawibul** [comment]
> I was able to implement this using fzf_action ` \ 'ctrl-y': ':%w !xclip -selection clipboard',` Thanks for this wonderful tool

This solution felt weird to me because:

- It depends on external command `xclip` to yank even though yanking is native to vim
  - on my machine the command name is not even `xclip`
- It also depends on environment having already been setup to sync system clipboard with vim yank register

So, I came up with an alternative:

```vimscript
function! s:set_clipboard(selected)
  let @+=join(a:selected, "\n")
  echo "Yanked " . len(a:selected) . " items to clipboard."
endfunction

" Add yanking filename to default action list
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit',
  \ 'ctrl-y': function('s:set_clipboard') }
```

- This selected text into yank `+` register directly without roundtrip to external command.
  - Syncing to system clipboard is a separate choice.
- Support yanking multiple lines. (effective if fzf option `-m` is enabled.)
