### ISSUE TITLE
Is it possible to get `--preview` to work with `:Buffers`? Or alternatively is it possible to disable it?

### ISSUE THREAD

**Issue by jsatk** [junegunn/fzf.vim#799]
- Category
    - [X] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [X] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [X] Vim
    - [ ] Neovim

I believe this is related to Issue #195 & #724, but not entirely sure since that isn't a lot of detail there. 

Basically, I'm wondering if there is a way to get fzf's `--preview` to work with `:Buffers` or `:Rg`. And if not, is there a way to disable the preview window when I'm viewing files in the `:Buffers` list? 

The screenshot below illustrates what I'm talking about.

<img width="1920" alt="Screen Shot 2019-04-19 at 3 48 19 PM" src="https://user-images.githubusercontent.com/1005550/56447046-f4158180-62ba-11e9-9db9-9d0ee32a1391.png">

**Comment by junegunn** [comment]
Preview is not enabled by default for Buffers. So I guess you have the option set in your FZF_DEFAULT_OPTS, which is a bad idea because fzf is a context-free text filter rather than a file selector. The command you have will fail whenever you use fzf to filter things that aren't files. e.g. `ps -ef | fzf`, `history | fzf`, etc.

So instead of setting preview option globally, only apply it on commands where preview makes sense.

Examples can be found the README page.

**Comment by jsatk** [comment]
Thank you @junegunn.

**Comment by jsatk** [comment]
Hey @junegunn. I read the README for both fzf.vim & fzf itself a few times. I'm still not understanding how to tell `fzf` to use `--preview` only for certain commands. I see that `fzf.vim` you can define custom vimscript commands, but that's not exactly what I'm looking for. 

I'm looking for a way to tell fzf when I run `:FZF` in Vim to show previews but when I run `:Buffers` not to. 

Is this possible?
