### ISSUE TITLE
Compability with vim-airline and vim-fugitive

### ISSUE THREAD

**Issue by timokau** [junegunn/fzf.vim#84]
Hi

I'm not sure wheter this is a problem caused by fzf.vim, but I hope somebody here can at least help me investigate what exaclty causes the problem.
Since recently (I don't know when exactly) I experienced some sort of "delay" when using the `Buffers` command. Delay maybe is the wrong word, but the terminal just stays empty until I press escape. After that it works normally.
When I quickly exit neovim after this behaviour I see the following error on the commandline:

```
Error detected while processing function 13:
line    7:
E37: No write since last change (add ! to override)
Error running cat "/tmp/nvimcjexRn/2"|/home/eisfreak7/.fzf/bin/fzf +m -x --tiebreak=index --ansi -d "\t" -n 2,1..2 --prompt="Buf> " --expect=ctrl-v,ctrl-x,ctrl-t > /tmp/nvimcjexRn/1%    
```

I tried disabling all my vim plugins except fzf.vim, and that solved the problem. Further trying revealed, that the incompabiltity is with tpope's `vim-fugitive`. I have no idea how that could be related, but disabling it solves the problem.

Any ideas?

**Comment by junegunn** [comment]
Fugitive buffers are set to be `bufhidden=delete` and vim will warn you if you try to hide the buffer when it's modified. A simple scenario to reproduce the problem.

- `vim foo bar`
- `:setlocal bufhidden=delete`
- `:normal! afoo`
- `:b 2`

I don't think there's something fzf.vim can do about it. Not allowing `:Buffers` command (or any other command that might hide the current buffer) in that case is not the solution, since you can open the selected entry in another window with `ctrl-x`, `ctrl-v`, or `ctrl-t`.

**Comment by Eisfreak7** [comment]
But the normal buffer that opens when I call `nvim file` shouldn't be a "fugitive buffer", should it?
I assume by fugitive buffer you mean the buffers that open with `Gdiff` etc.?
The problem I mentioned occurs in those "normal" buffers.

Also, `:Buffers` doesnt hide the buffer when called, but just when I select something. In my case, the delay happens directly after I type `:Buffers<Enter>`.
Maybe I've misunderstood you or didn't articulate the problem cleraly.

**Comment by junegunn** [comment]
Hmm, I'm not sure if I'm following you. Please provide exact steps to reproduce the problem.

**Comment by Eisfreak7** [comment]
Trying to create a minimal vimrc file which only loads the two conflicting plugins, I couldn't
reproduce the problem.
So it has to be something wrong with my setup, and its apparently just a concidence that it works
when I disable fugitive.
Sorry to bother you with this, I'll have to do some more testing to see what I did wrong.
Thank you for your work.

**Comment by Eisfreak7** [comment]
Okay, I isolated it.
To reproduce:
Save this file as `reproduce.vim` (or something similar`
```
call plug#begin('~/.config/nvim/plugged')
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-airline'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
call plug#end()

let g:fzf_nvim_statusline = 0
```
Execute
`nvim -u reproduce.vim`
`:Buffers`

Apparently the problem lies in the combination of the nvim_statusline config (of which I don't even know what it does, I must have blindly copied it from the readme), vim-airline (this seems to make sense) and vimtex (I have no idea what that has to do with it, but without it it works).

**Comment by junegunn** [comment]
Thanks.

1. `tpope/vim-airline` should be `bling/vim-airline`, right?
2. `g:fzf_nvim_statusline` is undocumented and is not on README page.
3. I can't reproduce the problem, with or without `g:fzf_nvim_statusline`
4. Why are you mentioning vimtex when it's not on reproduce.vim you provided?

**Comment by Eisfreak7** [comment]
1. Yes, that should be `bling/vim-airline`.
2. Well, that's weired. I was sure I saw  it there. But now I found the git commit where I introduced the line and remembered, that I actually stole my configuration from [this guy](https://www.reddit.com/r/neovim/comments/3oeko4/post_your_fzfvim_configurations/cvworyj) on reddit.
Again a reminder that you shouldn't just coppy stuff from other's vimrc without understanding every single line.
3. I apparently was confused, I meant vim-fugitive.

My mistake then, I guess when the configuration is undocumented this isn't really a bug, and since I'm still not even totally sure what it does I'll just remove the line and enjoy the new old responsiveness of fzf.
Thanks for helping me debug this and for developing these awesome plugins.

**Comment by junegunn** [comment]
> I guess when the configuration is undocumented this isn't really a bug

Although the variable is undocumented, it does prevent fzf.vim from updating the statusline of fzf window. And like I said above, I cannot reproduce the problem **with or without g:fzf_nvim_statusline**. Are you sure you can always reproduce the problem with the above configuration?

**Comment by Eisfreak7** [comment]
Now after I tried again I couldn't reproduce it myself and I though I am going insane.
But you *can* reproduce it, but only if you're inside of a git repo.
Not sure if it helps, but it cant hurt: [this is how it looks](https://asciinema.org/a/278myr3cdltibitrbsob86xgu)

**Comment by junegunn** [comment]
Okay, I could finally reproduce the problem locally. Profiling revealed that airline hangs:

```
FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    2             10.109629  <SNR>35_get_git_untracked()
  608              0.011779  <SNR>39_get_syn()
  304   0.019390   0.005502  airline#highlighter#get_highlight()
  126   0.017183   0.005232  airline#highlighter#exec()
  882              0.003906  <SNR>39_Get()
    9   0.025257   0.003050  9()
    4   0.014967   0.002295  airline#highlighter#highlight()
  304              0.002109  <SNR>39_get_array()
   51              0.002067  <SNR>43_get_accented_line()
    1              0.001849  <SNR>5_LoadFTPlugin()
    1   0.026094   0.001712  <SNR>15_execute_term()
   56   0.017017   0.001561  <SNR>39_exec_separator()
   70   0.001653   0.001461  <SNR>44_get_section()
   17   0.016904   0.001291  airline#check_mode()
   15   0.001068   0.000981  airline#extensions#whitespace#check()
   52   0.002486   0.000934  <SNR>44_add_section()
    1   0.001399   0.000820  fugitive#extract_git_dir()
   70              0.000689  <SNR>43_get_prev_group()
   42   0.014027   0.000647  <SNR>43_get_transitioned_seperator()
   14   0.003095   0.000608  <SNR>44_build_sections()
```

Interestingly, it is `system()` call that is not responding.

```
FUNCTION  <SNR>35_get_git_untracked()
Called 2 times
Total time:  10.109629
 Self time:  10.109629

count  total (s)   self (s)
    2              0.000003   let untracked = ''
    2              0.000003   if empty(a:file)
    1              0.000002     return untracked
                              endif
    1              0.000002   if has_key(s:untracked_git, a:file)
                                let untracked = s:untracked_git[a:file]
                              else
    1             10.109582     let output    = system('git status --porcelain -- '. a:file)
    1              0.000015     if output[0:1] is# '??' && output[3:-2] is? a:file
                                  let untracked = get(g:, 'airline#extensions#branch#notexists', g:airline_symbols.notexists)
                                endif
    1              0.000007     let s:untracked_git[a:file] = untracked
    1              0.000001   endif
    1              0.000002   return untracked
```

The problem goes away (as expected) if we disable fugitive integration of vim-airline.

```vim
let g:airline#extensions#branch#enabled = 0
```

Seems like an issue of Neovim but I have no idea where to start looking at.
(/cc @justinmk, @tarruda)

For now, you'll just have to remove `let g:fzf_nvim_statusline = 0` so that fzf disables airline on the window.

**Comment by justinmk** [comment]
Hmm, it is possible that `git status --porcelain` is showing a prompt? And, this issue wouldn't occur in Vim because fzf runs in tmux, right?

**Comment by junegunn** [comment]
@justinmk I've never used the option, so I can't be 100% sure, but it doesn't seem so according to the man page

```
       --porcelain
           Give the output in an easy-to-parse format for scripts. This is similar to the short output, but will remain stable across Git versions and regardless
           of user configuration. See below for details.
```

> this issue wouldn't occur in Vim because fzf runs in tmux, right?

Technically, it looks to me that it's not reproducible on Vim because `system('fzf-tmux')` is a blocking call, and airline doesn't get a chance to refresh the statusline.

**Comment by Eisfreak7** [comment]
That's an odd bug, I'm curious whrere the error originates from.
The "solution" of removing the option suffices for me though, so at least my problem is fixed.

**Comment by metalelf0** [comment]
Having the same issue, and profiling gives exactly the same output. Running `git status --porcelain` doesn't hang neither when ran from nvim (with `:let output = system('git status --porcelain -- new_file')`), from within a nvim term window or a plain terminal. Still, it appears to hang when being called within the airline function `<SNR>125_get_git_untracked()`. So strange!

**Comment by tombeynon** [comment]
This seems to be fixed for me in Neovim v0.1.4; I can use `let g:fzf_nvim_statusline = 0` without any problems.

**Comment by justinmk** [comment]
Tracked at https://github.com/neovim/neovim/issues/4487

**Comment by acro5piano** [comment]
Thanks, this issue thread helped me a lot!

In my case, the error occurred when I deleted this line in my `.vimrc`.

```
set hidden
```

So I add the line and fix the problem.
