### ISSUE TITLE
Override default options for Commands

### ISSUE THREAD

**Issue by neerajbadlani** [junegunn/fzf.vim#863]
- Category
    - [X ] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ X] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [X ] Vim
    - [ ] Neovim

IS there a way to provide differernt options for different commands other than modifying source either to override the defaults given / change some defaults .

**Comment by josefson** [comment]
I have a similar doubt where i know i could overide some command OPTIONS by overiding the command itself:
```
command! -bang -nargs=? -complete=dir Files
    \ call fzf#vim#files(
        \<q-args>,
        \{'options': [
            \'--bind=ctrl-g:top',
            \'--bind=ctrl-f:toggle-all',
            \'--bind=ctrl-b:backward-kill-word',
            \'--bind=ctrl-d:kill-word',
        \]},
        \<bang>0
    \)
```
However there are some options that I would like to apply globaly, would i have to overide every single command for this? Because i couldn't find an option dictionary where i could set default ones.

**Comment by junegunn** [comment]
> an option variable where i could set default ones

$FZF_DEFAULT_OPTS. See https://github.com/junegunn/fzf#environment-variables.
