### ISSUE TITLE
Question: new fzf feature reload inside vim

### ISSUE THREAD

**Issue by monkoose** [junegunn/fzf.vim#907]
- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion

Is it possible to use it and execute vim function or command? If yes, can you please explain how to do it. Because my several attempts failed with `[Command failed: ...]`.
Or by now only possible way is to imitate same command as `source` of fzf#run?
Thank you.

**Comment by junegunn** [comment]
> Because my several attempts failed

Please post the code you tried.

**Comment by junegunn** [comment]
```vim
function! RipgrepFzf(query, fullscreen)
  let command_fmt = 'rg --column --line-number --no-heading --color=always --smart-case %s || true'
  let initial_command = printf(command_fmt, shellescape(a:query))
  let reload_command = printf(command_fmt, '{q}')
  let options = {'options': ['--phony', '--query', a:query, '--bind', 'change:reload:'.reload_command]}
  call fzf#vim#grep(initial_command, 1, options, a:fullscreen)
endfunction

command! -nargs=1 -bang RF call RipgrepFzf(<q-args>, <bang>0)
```

This works for me. There is one problem though, that the command requires an initial query. This is to avoid starting ripgrep command for an empty query that can run for a very long time producing a lot of lines. And fzf cannot kill the initial command on "change", because it wasn't started by fzf process.

```sh
# fzf can kill subsequent-rg-command because it started it, but not initial-rg-command
initial-rg-command | fzf ... --bind 'change:reload:subsequent-rg-command'
```

A workaround is to set `FZF_DEFAULT_COMMAND` and start fzf without the standard input command.

```sh
# Temporarily replace FZF_DEFAULT_COMAND
prev_default=$FZF_DEFAULT_COMAND
export FZF_DEFAULT_COMMAND=initial-rg-command

# fzf can now kill both initial command and subsequent command
fzf ... --bind 'change:reload:subsequent-rg-command'

# Restore the default
export FZF_DEFAULT_COMMAND=$prev_default
```

However, `fzf#vim#grep` currently doesn't have an option for this mode of execution, but I can change that.

**Comment by junegunn** [comment]
Now this works well with the above commit.

```vim
function! RipgrepFzf(query, fullscreen)
  let command_fmt = 'rg --column --line-number --no-heading --color=always --smart-case %s || true'
  let initial_command = printf(command_fmt, shellescape(a:query))
  let reload_command = printf(command_fmt, '{q}')
  let options = {'options': ['--phony', '--query', a:query, '--bind', 'change:reload:'.reload_command]}
  call fzf#vim#grep(initial_command, 1, fzf#vim#with_preview(options), a:fullscreen)
endfunction

command! -nargs=* -bang RF call RipgrepFzf(<q-args>, <bang>0)
```

**Comment by monkoose** [comment]
Thank you.

**Comment by amebrahimi** [comment]
I have an issue about this topic when I try to start `:Rg` I get this error:
![image](https://user-images.githubusercontent.com/12514657/89127996-7c975000-d507-11ea-85e8-4adfcc8bf13c.png)
and here is my fzf vim settings file:
```
nnoremap <C-p> :GFiles<CR>
map <C-f> :Files<CR>
map <leader>b :Buffers<CR>
nnoremap <leader>g :Rg<CR>
nnoremap <leader>m :Marks<CR>

let g:fzf_layout = {'up':'~90%', 'window': { 'width': 0.8, 'height': 0.8,'yoffset':0.5,'xoffset': 0.5, 'highlight': 'Todo', 'border': 'sharp'  } }
let $FZF_DEFAULT_OPTS = '--layout=reverse --info=inline'
let $FZF_DEFAULT_COMMAND = 'rg --files --hidden'

let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }


let g:fzf_colors =
  \ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }

let g:fzf_tags_command='ctags -R'

"Get Files
command! -bang -nargs=? -complete=dir Files
            \ call fzf#vim#files(<q-args>, fzf#vim#with_preview({'options': ['--layout=reverse', '--info=inline']}), <bang>0)

" Get text in files with Rg
command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \   'rg --column --line-number --no-heading --color=always --smart-case'.shellescape(<q-args>), 1,
    \   fzf#vim#with_preview(), <bang>0)

function! RipgrepFzf(query, fullscreen)
    let command_fmt = 'rg --column --line-number --no-heading --color=always --smart-case %s || true'
    let initial_command = printf(command_fmt, shellescape(a:query))
    let reload_command = printf(command_fmt, '{q}')
    let options = {'options': ['--phony', '--query', a:query, '--bind', 'change:reload:'.reload_command]}
    call fzf#vim#grep(initial_command, 1, fzf#vim#with_preview(options), a:fullscreen)
endfunction

command! -nargs=* -bang RF call RipgrepFzf(<q-args>, <bang>0)

command! -bang -nargs=* GGrep
            \ call fzf#vim#grep(
            \ 'git grep --line-number '.shellescape(<q-args>), 0,
            \ fzf#vim#with_preview({'dir': systemlist('git rev-parse --show-toplevel')[0]}), <bang>0)

```

**Comment by upgradeQ** [comment]
@amebrahimi I had the same issue , turns out I've not installed rg , maybe it is the case? 
Since you on windows try running this command : `choco install ripgrep`

**Comment by tonybeyond** [comment]
I've the same issue as amebrahimi here above even though I've installed all required packages (arch distro). 

" This is the default extra key bindings
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }

" Enable per-command history.
" CTRL-N and CTRL-P will be automatically bound to next-history and
" previous-history instead of down and up. If you don't like the change,
" explicitly bind the keys to down and up in your $FZF_DEFAULT_OPTS.
let g:fzf_history_dir = '~/.local/share/fzf-history'

map <C-f> :Files<CR>
map <leader>b :Buffers<CR>
nnoremap <leader>g :Rg<CR>
nnoremap <leader>t :Tags<CR>
nnoremap <leader>m :Marks<CR>


let g:fzf_tags_command = 'ctags -R'
" Border color
let g:fzf_layout = {'up':'~90%', 'window': { 'width': 0.8, 'height': 0.8,'yoffset':0.5,'xoffset': 0.5, 'highlight': 'Todo', 'border': 'sharp' } }

let $FZF_DEFAULT_OPTS = '--layout=reverse --info=inline'
let $FZF_DEFAULT_COMMAND="rg --files --hidden"


" Customize fzf colors to match your color scheme
let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }

"Get Files
command! -bang -nargs=? -complete=dir Files
    \ call fzf#vim#files(<q-args>, fzf#vim#with_preview({'options': ['--layout=reverse', '--info=inline']}), <bang>0)


" Get text in files with Rg
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always --smart-case '.shellescape(<q-args>), 1,
  \   fzf#vim#with_preview(), <bang>0)

" Ripgrep advanced
"function! RipgrepFzf(query, fullscreen)
"  let command_fmt = 'rg --column --line-number --no-heading --color=always --smart-case %s || true'
"  let initial_command = printf(command_fmt, shellescape(a:query))
"  let reload_command = printf(command_fmt, '{q}')
"  let spec = {'options': ['--phony', '--query', a:query, '--bind', 'change:reload:'.reload_command]}

**Comment by DZ84** [comment]
I have this "Command failed..." issue shown in the screenshot above. It happens when I start :Rg with a command and it finds no matches (e.g. :Rg ksdfjsdjfskdlfsalkdjf). Start it with something where it will have hits (e.g. :Rg vim) and it's fine.

Would be nice if done more elegantly though.
