### ISSUE TITLE
function to toogle preview regardless of command

### ISSUE THREAD

**Issue by divagant-martian** [junegunn/fzf.vim#937]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Is there any way to achieve toggling a preview window on a fzf window in neovim after it's already launched? I know there are options that can be passed to fzf to have previews for certain commands via creating new ones (like `Ag!`) but what I am looking for would ideally be to have a mapping that toogles the preview regardless of the current command.

Is there anything like this? Or suggestion on how could it be implemented?
Thanks!

**Comment by zombiefungus** [comment]
Just to be clear, my questions comes since fzf windows are called from other plugins (LanguageClient-neovim is the one that really interests me) There, calling the find references function gives the result in a fzf window. This would be way more useful if, in order to decide if some of the result is what I'm looking for, instead of selecting it as a result (which leads to closing the fzf search) I could simply preview the file.

Thanks again

**Comment by junegunn** [comment]
Have you used fzf outside of Vim? `--preview` requires a command that knows how to "preview" the line:

```sh
whoami | fzf --preview 'echo Hello {}'
```

Which means, in order to "preview" something, you need a specific command tailored for that kind of input. Since we can't find a command that automagically shows detailed information for any kind of text,
globally enabling preview doesn't make much sense.
