### ISSUE TITLE
Expanded sample documentation on how to customize statusline?

### ISSUE THREAD

**Issue by chris-kahn** [junegunn/fzf.vim#939]
I think it would be good to expand a little bit on example statusline customization... what is possible to put there? Since long file paths get cut off when using the preview window, due to not enough screen width, I'd like to use a custom statusline that prints the full path of the currently selected file.

- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

**Comment by junegunn** [comment]
There's not much you can do. fzf is an external process to Vim/Neovim, so there's no direct way for Vim to communicate with it, so you can only put static stuff. So reading `:help 'statusline'` should suffice.

> Since long file paths get cut off when using the preview window, due to not enough screen width

Why don't you print the name in the preview window?

```sh
ls | fzf --preview 'echo {}; echo; cat {}'
```

If you use the preview script from this repository, it internally runs bat, so consider setting BAT_STYLE environment variable so that it prints more info.

```sh
export BAT_STYLE=full
```

![image](https://user-images.githubusercontent.com/700826/75988057-5a87aa80-5f34-11ea-8eb3-11da0931a6ac.png)
