### ISSUE TITLE
Is there any option for shortening file path? Like title of vim tab.

### ISSUE THREAD

**Issue by ChangWanHong** [junegunn/fzf.vim#960]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

Or is there any tweaks for that? I think if there is no option kind of that, then I apply 'sed' or something. Where should I change for this purpose?

<img width="1430" alt="스크린샷 2020-03-06 오후 4 09 45" src="https://user-images.githubusercontent.com/1219647/76060549-e812db00-5fc4-11ea-95b6-5364f5eae31c.png">

I wanna this to have shorter file path, like  "c/a/j/s/o/r/c/c/b/m/u/MediaNotification.java: (here: found line)"

**Comment by junegunn** [comment]
No, there's no such option. It's kind of tricky to implement

- You need a program to transform the streaming output of ripgrep
   ```sh
   rg --column --line-number --no-heading --color=always --smart-case "foo" | transformer
   ```
- But the output of "transformer" should still contain the original path along with the shortened path because we are going to need it to open that file.
- But you don't want to see the original path. fzf provides `--with-nth` option that allows you to hide certain fields (in this case, the original path).
- The sink function of `fzf#vim#grep` will look at the first three fields for the original path, line number, and column number. So make sure that the "transformer" keep the ordering of the three fields. For example,
    ```
    FILE:LINE:COL:TEXT => FILE:LINE:COL:SHORTPATH:LINE:COL:TEXT
                          (   HIDDEN   )-----------------------
    ```

```vim
" TODO: Implement a program that shortens the path in each line
let transformer = "| awk -F: 'BEGIN { OFS = FS } {$3 = $3 \":shortened-path:\" $2 \":\" $3; print}'"

command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   "rg --column --line-number --no-heading --color=always --smart-case "..shellescape(<q-args>)..transformer,
  \   1,
  \   { 'options': '--delimiter=: --with-nth=4..' },
  \   <bang>0)
```

**Comment by ChangWanHong** [comment]
@junegunn Thank you! Your reply helps me so much.
