### ISSUE TITLE
Getting ripgrep to work with fzf_action config

### ISSUE THREAD

**Issue by rattletat** [junegunn/fzf.vim#968]
Hey there!

I cannot get the fzf_action configurtion to work with ripgrep. The command below works fine using `:Files` and `:Lines`, but does not work with `:Rg` for some reason. Instead of copying the basename, it opens the quickfix window.

Any ideas / can some cross check this? Thanks a lot!

```vim
command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \ 'rg --hidden --ignore-case --line-number --column --color=always -e '.shellescape(<q-args>).' '.fnameescape(expand('%:p:h')), 1,
    \ fzf#vim#with_preview({'options': '--delimiter : --nth 4.. --no-sort'}), <bang>0)

function! s:get_basename(lines)
    let basename = system('basename '.shellescape(a:lines[0]).' .md')
    let basename = substitute(l:basename, '[\r\n]*$', '', '')
    let @+ = basename
endfunction

let g:fzf_action = {
    \ 'ctrl-b': function('s:get_basename'),
    \ }

let $FZF_DEFAULT_OPTS = '--bind ctrl-a:select-all'
```

**Comment by junegunn** [comment]
Function values in `g:fzf_action` currently are not supported. I explained why in https://github.com/junegunn/fzf/issues/1885.

Also note that even if we make `g:fzf_action` work with specs with custom sinks, your `s:get_basename` will not work in this case, because each line of ripgrep is not a proper file path:

```vim
let line = 'somefile:100:200: line content'
let basename = system('basename '.shellescape(line).' .md')
```

Which means, your function should work with any kind of input (e.g. `:Colors`, `:Snippets`, `:Commands`), and it's just impossible, so that's why `g:fzf_action` only works with file paths.
