### ISSUE TITLE
Overridden preview option in spec

### ISSUE THREAD

**Issue by mroavi** [junegunn/fzf.vim#975]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

After running:

```vim
fzf#vim#with_preview({'options': ['--no-reverse', '--no-height', '--preview-window', 'up:60%']})
```

I get this results:

```vim
{'options': ['--no-reverse', '--no-height', '--preview-window', 'up:60%', '--preview-window', 'right', '--preview', '''/home/mroavi/.homesick/repos/dotfiles/home/.vim/plugged/fzf.vim/bin/preview.sh'' {}']}
```
My problem is that `'--preview-window', 'right'` is overiding my passed `'up:60%'` option. How can I avoid this? Where is this `'right'` option being appended?

I also noticed that:
```vim
fzf#vim#with_preview('up:60%')
```
results in:
```vim
{'options': ['--preview-window', 'down:60%', '--preview', '''/home/mroavi/.homesick/repos/dotfiles/home/.vim/p
lugged/fzf.vim/bin/preview.sh'' {}']}
```
which is more in line with what I want since it doesn't have the `'right'` option appended. However, I also want to be able to pass the other options.

I made sure to include this in my `.vimrc`:

```vim
" Empty value to disable preview window altogether
let g:fzf_preview_window = ''
``` 

My complete re-definition of `Files`:

```vim
command! -nargs=? -bang -complete=dir Files
	\ call fzf#vim#files(<q-args>,
	\                    <bang>0 ? fzf#vim#with_preview({'options': ['--no-reverse', '--no-height', '--preview-window', 'up:60%']})
	\                            : {},
	\                    <bang>0)
```

**Comment by junegunn** [comment]
The function signature of `fzf#vim#with_preview` is 

https://github.com/junegunn/fzf.vim/blob/d4d36b412bdc53e8bdaf0e2714a2227f51781d68/autoload/fzf/vim.vim#L77-L78

so you can just pass the preview window spec as the second parameter.

```vim
echo fzf#vim#with_preview({'options': ['--no-reverse']}, 'up:60%')
  " {'options': ['--no-reverse', '--no-height', '--preview-window', 'up:60%', '--preview', '''.../preview.sh'' {}']}
```

The extra string parameter is for binding `toggle-preview` action to the key.

```vim
" Preview window hidden by default, but can be toggleable with `?' key
echo fzf#vim#with_preview({'options': ['--no-reverse', '--no-height']}, 'up:60%:hidden', '?')
```

But I decided not to mention these extra parameters in the README page at some point (https://github.com/junegunn/fzf.vim/commit/6eda9fd38a778b203a8e1d0693ae85c657fd7a35), because I'd started to question their usefulness as we can just put those options manually in the spec dictionary.

But you just found out that it doesn't work as expected:

```vim
echo fzf#vim#with_preview({'options': ['--no-reverse', '--preview-window', 'up:60%']})
```

Let me fix this.

**Comment by junegunn** [comment]
It should be fixed now.
