### ISSUE TITLE
Height option in spec does not have an effect

### ISSUE THREAD

**Issue by mroavi** [junegunn/fzf.vim#976]
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [x] I have read through the manual page of fzf (`man fzf`)
- [x] I have searched through the existing issues

The `'height', '80%'` option in the following command does not have any effect.
```vim
command! -nargs=? -bang -complete=dir Files call fzf#vim#files(
    \ <q-args>,
    \ fzf#vim#with_preview({'options': ['--no-reverse', '--height', '80%', '--preview-window', 'right:60%']}),
    \ <bang>0)
```
Initially I had
```vim
let g:fzf_layout = { 'down': '~20%' }
```
on my `.vimrc`. I removed it to see if it was overriding it. However, it still did not have any effect. Apparently, FZF remembers the old `height` value assigned to `g:fzf_layout`. How can I enforce a custom `height` option for a given command? For example, I prefer `:Files` or `:Gr` to have a larger height than `:Commands`.

**Comment by junegunn** [comment]
`--height` option makes sense only when you run fzf outside of Vim. When we run fzf inside Vim, we open it in a terminal buffer, and fzf should use the whole screen estate of the buffer, so we enforce `--no-height`.

Layout options for Vim are described in

https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfrun

```vim
call fzf#run(fzf#vim#with_preview({'options': ['--reverse'], 'down': '80%'}))
call fzf#run(fzf#vim#with_preview({'options': ['--reverse'], 'left': '80%'}))
```

**Comment by mroavi** [comment]
@junegunn Thanks for the answer, I have it working now. The reason why I got confused was because `''--no-height'` does have an effect. Would it make sense to ignore that option as well?

**Comment by junegunn** [comment]
Well, it's complicated, you probably don't really want to know the nitty-gritty :)

On regular Vim, with `down` layout, fzf does not open in a terminal buffer, but using `--height` option. So in this particular case, you can get the impression that `--height` or `--no-height` has an effect. But it's an exception, because `--height` cannot support `left`, `right`, or `up` layouts, so we use terminal buffers in those cases.

On the other hand, on Neovim, fzf always opens in a terminal buffer because `--height` doesn't work well with Neovim. So `--height` or `--no-height` doesn't have any effect on Neovim.

You can read more about this in https://github.com/junegunn/fzf/issues/1860
